objects/Aggregated_Case_Time_Log__c.object
<CustomObject>
    <description>This object is used to hold aggregated Case Time Log records.  A batch process updates this object based on values in custom meta data settings.</description>
    <fields>
        <fullName>Aggregation_Name__c</fullName>
        <description>The name of a particular aggregration made up of the Start &lt;field&gt; and End &lt;field&gt; text: Owner - Owner New,  Status - Status New,   Owner - Status.</description>
        <inlineHelpText>The name of a particular aggregration made up of the Start &lt;field&gt; and End &lt;field&gt; text: Owner - Owner New,  Status - Status New,   Owner - Status.</inlineHelpText>
        <label>Aggregation Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Status_Group__c</fullName>
        <description>The Status Group that this aggregation belongs to.  Usually this is either Company or Customer.</description>
        <inlineHelpText>The Status Group that this aggregation belongs to.  Usually this is either Company or Customer.</inlineHelpText>
        <label>Case Status Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Owner_Type__c</fullName>
        <description>This field indicates whether the Parent record Owner was a User or a Queue.</description>
        <inlineHelpText>This field indicates whether the Parent record Owner was a User or a Queue.</inlineHelpText>
        <label>Owner Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Owner_New__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The User that is the Owner of the Parent Object record (e.g. Case Owner) when the time log is closed or ended.</description>
        <inlineHelpText>The User that is the Owner of the Parent Object record (e.g. Case Owner) when the time log is closed or ended.</inlineHelpText>
        <label>Parent Owner New</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Aggregated_Case_Time_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The User that is the Owner of the Parent Object record ( e.g. Case Owner) when the time log is created.</description>
        <inlineHelpText>The User that is the Owner of the Parent Object record (e.g. Case Owner) when the time log is created.</inlineHelpText>
        <label>Parent Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Aggregated_Case_Time_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Aggregated Case Time Log</label>
    <nameField>
        <displayFormat>ACTL-{000000}</displayFormat>
        <label>Aggregated Case Time Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aggregated Case Time Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Aggregation_Batch_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Batch_End_Date__c</fullName>
        <description>This is the ending Date time for the batch.   NOTE:  12:00 AM  on the first day of the following month will insure you get everthing for the previous month.   e.g.  urn up to  11:59:59 PM on the last day of the month.</description>
        <inlineHelpText>This is the ending Date time for the batch.   NOTE:  12:00 AM  on the first day of the following month will insure you get everthing for the previous month.   e.g.  urn up to  11:59:59 PM on the last day of the month.</inlineHelpText>
        <label>Batch End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Batch_Start_Date__c</fullName>
        <description>This is the start Date Time for the Batch.  All the Time Log records after this date time and before the end time are included in the aggregation batch</description>
        <inlineHelpText>This is the start Date Time for the Batch.  All the Time Log records after this date time and before the end time are included in the aggregation batch</inlineHelpText>
        <label>Batch Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Aggregation Batch Settings</label>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Power of one field for reports</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Case_Time_Log__c.object
<CustomObject>
    <description>Time Log records for the Case object. A snapshot of Case fields and time calculations when closed.</description>
    <fields>
        <fullName>Business_Hours_Duration__c</fullName>
        <description>Calculate business time duration when a Time Log record &quot;closes&quot; in seconds.</description>
        <inlineHelpText>Number of seconds this Time Log record had during business hours.</inlineHelpText>
        <label>Business Hours Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calendar_Duration__c</fullName>
        <description>Calculate calendar time duration when a Time Log record &quot;closes&quot;</description>
        <inlineHelpText>Number of seconds this Time Log record had in calendar time. Calendar time includes both business hours time and non business hours time.</inlineHelpText>
        <label>Calendar Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Status_Change__c</fullName>
        <description>If  Case Status equals Case Status New set to 0, else set to 1.</description>
        <formula>IF( Case_Status__c = Case_Status_New__c, 0, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>1 in this field indicates that the Case Status has changed.</inlineHelpText>
        <label>Case Status Change</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Status_Group__c</fullName>
        <description>This field allows categorization of the Case Status values into Customer or Company for reporting purposes.  Edit the formula below as required to account for the values in the Case Status field.</description>
        <formula>/* EDIT THIS FORMULA AS REQUIRED TO MATCH THE CASE STATUS FIELD VALUES */
/* THIS IS AN EXAMPLE ONLY */
/*                         */
Case ( Case_Status__c , 
&quot;Team Assistance Needed&quot;,&quot;Company&quot;, 
&quot;Awaiting Service Excellence Review&quot;,&quot;Company&quot;, 
&quot;POS Team&quot;,&quot;Company&quot;, 
&quot;Pending Fraud Team&quot;,&quot;Company&quot;, 
&quot;System Issue&quot;,&quot;Company&quot;, 
&quot;Awaiting Customer Response&quot;,&quot;Customer&quot;, 
&quot;Awaiting Internal Response&quot;,&quot;Company&quot;, 
&quot;Response Received&quot;,&quot;Company&quot;, 
&quot;New&quot;,&quot;Company&quot;, 
&quot;In Progress&quot;,&quot;Company&quot;, 
&quot;Closed&quot;,&quot;Customer&quot;, 
&quot;Company&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field allows categorization of the Case Status values into Customer or Company for reporting purposes.</inlineHelpText>
        <label>Case Status Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Status_New__c</fullName>
        <description>The value of the Case Status field when the Time Log record was closed / ended.</description>
        <inlineHelpText>The value of the Case Status field when the Time Log record was closed / ended.</inlineHelpText>
        <label>Case Status New</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Status__c</fullName>
        <description>The value of the Case Status field when the Time Log record was created.</description>
        <inlineHelpText>The value of the Case Status field when the Time Log record was created.</inlineHelpText>
        <label>Case Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent object lookup</description>
        <inlineHelpText>This is the link up to the Case record (parent record) for this Time Log record.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Time Logs</relationshipLabel>
        <relationshipName>Case_Time_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>The date time that this time log record was closed or ended.</description>
        <inlineHelpText>The date time that this time log record was closed or ended.</inlineHelpText>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Aggregated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates if this record is already considered in aggregation logic</description>
        <inlineHelpText>This field indicates if this record is already considered in aggregation logic</inlineHelpText>
        <label>Aggregated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Owner_Type__c</fullName>
        <description>This field indicates whether the Parent record Owner was a User or a Queue.</description>
        <inlineHelpText>This field indicates whether the Parent record Owner was a User or a Queue.</inlineHelpText>
        <label>Owner Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Owner_Change__c</fullName>
        <description>Set value to 1 if Parent Owner is not the same as Parent Owner New</description>
        <formula>IF ( Parent_Owner__c =  Parent_Owner_New__c, 0, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Set value to 1 if Parent Owner is not the same as Parent Owner New.   This allows the counting of how many times Case Ownship changed.</inlineHelpText>
        <label>Parent Owner Change</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Owner_New__c</fullName>
        <description>This field contains the value of the Parent record Owner that caused this Time Log record to be &quot;closed&quot;. This is the text value of the Case Owner field (Parent record Owner). This field can be used for reporting as it includes both the User and Queue names in the same field. Changes to other fields being tracked will cause this field to be updated, but not changed when the Time Log record is created for other changes.</description>
        <inlineHelpText>This is the Owner of the Parent record at the time the time log record was closed.  This value is updated when the Parent record&apos;s Owner changes, otherwise it doesn&apos;t change, since the Owner hasn&apos;t actually changed on the Parent record.</inlineHelpText>
        <label>Parent Owner New</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Owner_User_New__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User object lookup, indicating the User that was the Owner of the Case record at the time the Time Log record was CLOSED; the new &quot;Owner&quot; when the owner of the parent record changes.</description>
        <inlineHelpText>User object lookup, indicating the User that was the Owner of the Case record at the time the Time Log record was CLOSED; the new &quot;Owner&quot; when the owner of the parent record changes.</inlineHelpText>
        <label>Case Owner New - User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Time_Logs_Owner_User_New</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Owner_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User object lookup from the Case Owner field at time of Time Log creation</description>
        <inlineHelpText>User object lookup, indicating the User that was the Owner of the Case record at the time the Time Log record was created.</inlineHelpText>
        <label>Case Owner - User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Time_Logs_Owner_User</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Owner__c</fullName>
        <description>This is the text value of the Case Owner field (Parent record Owner). This field can be used for reporting as it includes both the User and Queue names in the same field.</description>
        <inlineHelpText>This is the text value of the Case Owner field (Parent record Owner). This field can be used for reporting as it includes both the User and Queue names in the same field.</inlineHelpText>
        <label>Parent Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Time Log</label>
    <nameField>
        <displayFormat>CTL-{00000}</displayFormat>
        <label>Time Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Time Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/todft_AggregatedCaseTimeLogBatch.cls
/**
 * Batch class processes Case Time Log records created between two dates stored in
 * Aggregation Batch Settings and create Aggregated Time Log records.
 * @author Shubham Jain, Traction on Demand
 * @date 2019-07-18
 */

global class todft_AggregatedCaseTimeLogBatch implements
                Database.Batchable<sObject>, Database.Stateful {

    global Map<String, Aggregated_Case_Time_Log__c> insertedAggregatedTimeLogs = new Map<String, Aggregated_Case_Time_Log__c>();

    private Aggregation_Batch_Settings__c aggregationBatchSettings = todft_AggregatedCaseTimeLogBatchUtility.aggregationBatchSettings;

    /**
	 * @description Query data from Case Time Log object.
	 * @param bc - BatchableContext
	 */
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String whereClause = ' End_Time__c != NULL AND Is_Aggregated__c = false';
        //If check if custom setting record is null
        if (aggregationBatchSettings.Batch_Start_Date__c != null && aggregationBatchSettings.Batch_End_Date__c != null) {
            String startDate = (aggregationBatchSettings.Batch_Start_Date__c).formatGMT(todft_TimeLogAggregationConstants.GMT_FORMAT);
            String endDate = (aggregationBatchSettings.Batch_End_Date__c).formatGMT(todft_TimeLogAggregationConstants.GMT_FORMAT);
            whereClause = whereClause + ' ' + ' AND CreatedDate >= ' + startDate + ' AND CreatedDate < ' + endDate;
        }
        String queryString = 'SELECT Business_Hours_Duration__c, Calendar_Duration__c, Case__c, Case_Status__c, ' +
                'Case_Status_New__c, Case_Status_Group__c, Owner_Type__c, Parent_Owner__c, ' +
                'Parent_Owner_User__c, Parent_Owner_User_New__c, Case_Status_Change__c, ' +
                'Parent_Owner_Change__c, Parent_Owner_New__c, CreatedDate ' +
                'FROM Case_Time_Log__c WHERE' + ' ' + whereClause + ' Order By CreatedDate';
        return Database.getQueryLocator(queryString);
    }

    /**
	 * @description Query data from Case Time Log object
	 * @param bc - BatchableContext
	 * @param scope - Case Time Log records to process
	 */
    global void execute(Database.BatchableContext bc, List<Case_Time_Log__c> scope) {

        Map<String, List<Case_Time_Log__c>> caseTimeLogsByKeyStrings = new Map<String, List<Case_Time_Log__c>>();
        List<Aggregated_Case_Time_Log__c> aggregatedCaseTimeLogs = new List<Aggregated_Case_Time_Log__c>();
        List<Aggregated_Case_Time_Log__c> aggregatedTimeLogsToUpsert = new List<Aggregated_Case_Time_Log__c>();
        Map<String, Integer> statusChangeCountByCase = new Map<String, Integer>();
        Map<String, Integer> ownerChangeCountByCase = new Map<String, Integer>();
        Set<Id> caseIds = new Set<Id>();

        for (Case_Time_Log__c ctLog : scope) {

            //Status - Status New Aggregation
            if (ctLog.Case_Status__c != null
                    && ctLog.Case_Status_New__c != null
                    && ctLog.Case_Status__c != ctLog.Case_Status_New__c) {

                List<Case_Time_Log__c> caseTimeLogs =
                        caseTimeLogsByKeyStrings.get(todft_TimeLogAggregationConstants.STATUS_TYPE_AGGREGATION_IDENTIFIER + ctLog.Case_Status__c + ' - ' + ctLog.Case_Status_New__c);
                if (caseTimeLogs == null)
                    caseTimeLogs = new List<Case_Time_Log__c>();
                caseTimeLogs.add(ctLog);
                caseTimeLogsByKeyStrings.put(todft_TimeLogAggregationConstants.STATUS_TYPE_AGGREGATION_IDENTIFIER + ctLog.Case_Status__c + ' - ' + ctLog.Case_Status_New__c, caseTimeLogs);
            }

            //Owner - Owner New Aggregation
            if ((ctLog.Parent_Owner__c != null
                    && ctLog.Parent_Owner_New__c != null
                    && !ctLog.Parent_Owner__c.equals(ctLog.Parent_Owner_New__c))) {

                List<Case_Time_Log__c> caseTimeLogs = caseTimeLogsByKeyStrings.get(todft_TimeLogAggregationConstants.OWNER_TYPE_AGGREGATION_IDENTIFIER + ctLog.Parent_Owner__c + ' - ' + ctLog.Parent_Owner_New__c);
                if (caseTimeLogs == null)
                    caseTimeLogs = new List<Case_Time_Log__c>();
                caseTimeLogs.add(ctLog);
                caseTimeLogsByKeyStrings.put(todft_TimeLogAggregationConstants.OWNER_TYPE_AGGREGATION_IDENTIFIER + ctLog.Parent_Owner__c + ' - ' + ctLog.Parent_Owner_New__c, caseTimeLogs);
            }

            //Owner - Status Aggregation
            if (ctLog.Parent_Owner__c != null
                    && ctLog.Case_Status_New__c != null
                    && ctLog.Case_Status__c != ctLog.Case_Status_New__c) {

                List<Case_Time_Log__c> caseTimeLogs = caseTimeLogsByKeyStrings.get(todft_TimeLogAggregationConstants.OWNER_STATUS_TYPE_AGGREGATION_IDENTIFIER + ctLog.Parent_Owner__c + ' - ' + ctLog.Case_Status__c);
                if (caseTimeLogs == null)
                    caseTimeLogs = new List<Case_Time_Log__c>();
                caseTimeLogs.add(ctLog);
                caseTimeLogsByKeyStrings.put(todft_TimeLogAggregationConstants.OWNER_STATUS_TYPE_AGGREGATION_IDENTIFIER + ctLog.Parent_Owner__c + ' - ' + ctLog.Case_Status__c, caseTimeLogs);
            }

            //Populate caseIds Set
            if (ctLog.Case__c != null) {
                caseIds.add(ctLog.Case__c);
            }
            //Check if it is a Status Change log and create map to count total status changes for each case
            if (ctLog.Case_Status_Change__c == 1) {
                Integer count = statusChangeCountByCase.get(ctLog.Case__c);
                if (count == null)
                    count = 0;
                count++;
                statusChangeCountByCase.put(ctLog.Case__c, count);
            }
            //Check if it is a Owner Change log and create map to count total owner changes for each case
            if (ctLog.Parent_Owner_Change__c == 1) {
                Integer count = ownerChangeCountByCase.get(ctLog.Case__c);
                if (count == null)
                    count = 0;
                count++;
                ownerChangeCountByCase.put(ctLog.Case__c, count);
            }

        }

        List<Integer> statusCountList = statusChangeCountByCase.values();
        statusCountList.sort();
        List<Integer> ownerCountList = ownerChangeCountByCase.values();
        ownerCountList.sort();

        //Call Utility method to create one touches type aggregation record.
        if (!scope.isEmpty()) {
            if (!caseTimeLogsByKeyStrings.isEmpty()) {
                aggregatedCaseTimeLogs = todft_AggregatedCaseTimeLogBatchUtility.getAggregatedCaseTimeLogs(caseTimeLogsByKeyStrings);
            }
            Aggregated_Case_Time_Log__c touchesAggregation =
                    todft_AggregatedCaseTimeLogBatchUtility.getTouchesAggregationRecord(scope.size(), caseIds.size(), statusCountList, ownerCountList);
            aggregatedCaseTimeLogs.add(touchesAggregation);
            aggregatedTimeLogsToUpsert = todft_AggregatedCaseTimeLogBatchUtility.updateExistingRecords(aggregatedCaseTimeLogs, insertedAggregatedTimeLogs);
        }

        if (!aggregatedTimeLogsToUpsert.isEmpty()) {
            try {
                upsert aggregatedTimeLogsToUpsert;
                for (Aggregated_Case_Time_Log__c thisLog : aggregatedTimeLogsToUpsert) {
                    insertedAggregatedTimeLogs.put(thisLog.Aggregation_Name__c, thisLog);
                }
            } catch (DmlException e) {
                System.debug('Unhandled exception occurred ' + e.getMessage());
            }
        }

    }

    /**
	 * @description Sends email to user when batch is processed.
	 * @param bc - BatchableContext
	 */

    global void finish(Database.BatchableContext bc) {

        AsyncApexJob a = [Select Id, Status,ExtendedStatus,NumberOfErrors, JobItemsProcessed,
                TotalJobItems, CreatedBy.Email
        from AsyncApexJob where Id =:BC.getJobId()];

        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {a.CreatedBy.Email};
        mail.setToAddresses(toAddresses);
        mail.setSubject('Case Time Logs Aggregation Batch ' + a.Status);
        mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems +
                ' batches with '+ a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}