objects/Aggregated_Case_Time_Log__c.object
<CustomObject>
    <description>This object is used to hold aggregated Case Time Log records.  A batch process updates this object based on values in custom meta data settings.</description>
    <fields>
        <fullName>Aggregation_End_Date__c</fullName>
        <description>The end date for the range of days to be aggregated.</description>
        <inlineHelpText>The end date for the range of days to be aggregated.</inlineHelpText>
        <label>Aggregation End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Aggregation_Name__c</fullName>
        <description>The name of a particular aggregration made up of the Start &lt;field&gt; and End &lt;field&gt; text: Owner - Owner New,  Status - Status New,   Owner - Status.</description>
        <inlineHelpText>The name of a particular aggregration made up of the Start &lt;field&gt; and End &lt;field&gt; text: Owner - Owner New,  Status - Status New,   Owner - Status.</inlineHelpText>
        <label>Aggregation Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Aggregation_Start_Date__c</fullName>
        <description>The start date for the range of days to be aggregated.</description>
        <inlineHelpText>The start date for the range of days to be aggregated.</inlineHelpText>
        <label>Aggregation Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Aggregation_Type__c</fullName>
        <description>The type of a particular aggregration made up of the Start and End field labels: Owner - Owner New,  Status - Status New,   Owner - Status.</description>
        <inlineHelpText>The type of a particular aggregration made up of the Start and End field labels: Owner - Owner New,  Status - Status New,   Owner - Status.</inlineHelpText>
        <label>Aggregation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Owner - Owner New</fullName>
                </value>
                <value>
                    <fullName>Status - Status New</fullName>
                </value>
                <value>
                    <fullName>Owner - Status</fullName>
                </value>
                <value>
                    <fullName>Touches</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Hours_Duration_Maximum__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The maximum business hours time, in seconds, across the Cases for this aggregation.</description>
        <inlineHelpText>The maximum business hours time, in seconds, across the Cases for this aggregation.</inlineHelpText>
        <label>Business Hours Duration Maximum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Hours_Duration_Minimum__c</fullName>
        <description>The minimum business hours time, in seconds, across the Cases for this aggregation.</description>
        <inlineHelpText>The minimum business hours time, in seconds, across the Cases for this aggregation.</inlineHelpText>
        <label>Business Hours Duration Minimum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Hours_Duration_Sum__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The sum of business hours time, in seconds, across the Cases for this aggregation.</description>
        <inlineHelpText>The sum of business hours time, in seconds, across the Cases for this aggregation.</inlineHelpText>
        <label>Business Hours Duration Sum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calendar_Hours_Maximum__c</fullName>
        <description>The maximum calendar time, in seconds, across the Cases for this aggregation.</description>
        <inlineHelpText>The maximum calendar time, in seconds, across the Cases for this aggregation.</inlineHelpText>
        <label>Calendar Hours Maximum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calendar_Hours_Minimum__c</fullName>
        <description>The minimum calendar time, in seconds, across the Cases for this aggregation.</description>
        <inlineHelpText>The minimum calendar time, in seconds, across the Cases for this aggregation.</inlineHelpText>
        <label>Calendar Hours Minimum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calendar_Hours_Sum__c</fullName>
        <description>The sum of calendar time, in seconds, across the Cases for this aggregation.</description>
        <inlineHelpText>The sum of calendar time, in seconds, across the Cases for this aggregation.</inlineHelpText>
        <label>Calendar Hours Sum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Status_Group__c</fullName>
        <description>The Status Group that this aggregation belongs to.  Usually this is either Company or Customer.</description>
        <inlineHelpText>The Status Group that this aggregation belongs to.  Usually this is either Company or Customer.</inlineHelpText>
        <label>Case Status Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_of_Time_Logs_Touched__c</fullName>
        <description>The count of Time Logs used in the touches calculations.  The total number of Time Logs in the aggregation date range.</description>
        <inlineHelpText>The count of Time Logs used in the touches calculations.  The total number of Time Logs in the aggregation date range.</inlineHelpText>
        <label>No. of Time Logs Touched</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Cases__c</fullName>
        <description>The number of Cases included in an aggregation date range for a particular aggregation.</description>
        <inlineHelpText>The number of Cases included in an aggregation date range for a particular aggregation.</inlineHelpText>
        <label>Number of Cases</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner_Type__c</fullName>
        <description>This field indicates whether the Parent record Owner was a User or a Queue.</description>
        <inlineHelpText>This field indicates whether the Parent record Owner was a User or a Queue.</inlineHelpText>
        <label>Owner Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_New__c</fullName>
        <description>The Status value of the Parent Object record (e.g. Case Status) when the time log is closed or ended.</description>
        <inlineHelpText>The Status value of the Parent Object record (e.g. Case Status) when the time log is closed or ended.</inlineHelpText>
        <label>Status New</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The Status value of the Parent Object record (e.g. Case Status) when the time log is created or started.</description>
        <inlineHelpText>The Status value of the Parent Object record (e.g. Case Status) when the time log is created or started.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Aggregated Case Time Log</label>
    <nameField>
        <displayFormat>ACTL-{000000}</displayFormat>
        <label>Aggregated Case Time Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aggregated Case Time Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Aggregation_Batch_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Batch_End_Date__c</fullName>
        <description>This is the ending Date time for the batch.   NOTE:  12:00 AM  on the first day of the following month will insure you get everthing for the previous month.   e.g.  urn up to  11:59:59 PM on the last day of the month.</description>
        <inlineHelpText>This is the ending Date time for the batch.   NOTE:  12:00 AM  on the first day of the following month will insure you get everthing for the previous month.   e.g.  urn up to  11:59:59 PM on the last day of the month.</inlineHelpText>
        <label>Batch End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Batch_Start_Date__c</fullName>
        <description>This is the start Date Time for the Batch.  All the Time Log records after this date time and before the end time are included in the aggregation batch</description>
        <inlineHelpText>This is the start Date Time for the Batch.  All the Time Log records after this date time and before the end time are included in the aggregation batch</inlineHelpText>
        <label>Batch Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Aggregation Batch Settings</label>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Power of one field for reports</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Case_Time_Log__c.object
<CustomObject>
    <description>Time Log records for the Case object. A snapshot of Case fields and time calculations when closed.</description>
    <fields>
        <fullName>Business_Hours_Duration__c</fullName>
        <description>Calculate business time duration when a Time Log record &quot;closes&quot; in seconds.</description>
        <inlineHelpText>Number of seconds this Time Log record had during business hours.</inlineHelpText>
        <label>Business Hours Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calendar_Duration__c</fullName>
        <description>Calculate calendar time duration when a Time Log record &quot;closes&quot;</description>
        <inlineHelpText>Number of seconds this Time Log record had in calendar time. Calendar time includes both business hours time and non business hours time.</inlineHelpText>
        <label>Calendar Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Status_Group__c</fullName>
        <description>This field allows categorization of the Case Status values into Customer or Company for reporting purposes.  Edit the formula below as required to account for the values in the Case Status field.</description>
        <formula>/* EDIT THIS FORMULA AS REQUIRED TO MATCH THE CASE STATUS FIELD VALUES */
/* THIS IS AN EXAMPLE ONLY */
/*                         */
Case ( Case_Status__c , 
&quot;Team Assistance Needed&quot;,&quot;Company&quot;, 
&quot;Awaiting Service Excellence Review&quot;,&quot;Company&quot;, 
&quot;POS Team&quot;,&quot;Company&quot;, 
&quot;Pending Fraud Team&quot;,&quot;Company&quot;, 
&quot;System Issue&quot;,&quot;Company&quot;, 
&quot;Awaiting Customer Response&quot;,&quot;Customer&quot;, 
&quot;Awaiting Internal Response&quot;,&quot;Company&quot;, 
&quot;Response Received&quot;,&quot;Company&quot;, 
&quot;New&quot;,&quot;Company&quot;, 
&quot;In Progress&quot;,&quot;Company&quot;, 
&quot;Closed&quot;,&quot;Customer&quot;, 
&quot;Company&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field allows categorization of the Case Status values into Customer or Company for reporting purposes.</inlineHelpText>
        <label>Case Status Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Status_New__c</fullName>
        <description>The value of the Case Status field when the Time Log record was closed / ended.</description>
        <inlineHelpText>The value of the Case Status field when the Time Log record was closed / ended.</inlineHelpText>
        <label>Case Status New</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Status__c</fullName>
        <description>The value of the Case Status field when the Time Log record was created.</description>
        <inlineHelpText>The value of the Case Status field when the Time Log record was created.</inlineHelpText>
        <label>Case Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent object lookup</description>
        <inlineHelpText>This is the link up to the Case record (parent record) for this Time Log record.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Time Logs</relationshipLabel>
        <relationshipName>Case_Time_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_Type__c</fullName>
        <description>This field indicates whether the Parent record Owner was a User or a Queue.</description>
        <inlineHelpText>This field indicates whether the Parent record Owner was a User or a Queue.</inlineHelpText>
        <label>Owner Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Time Log</label>
    <nameField>
        <displayFormat>CTL-{00000}</displayFormat>
        <label>Time Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Time Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/todft_AggregatedCaseTimeLogBatchUtility.cls
/**
 * Utility class for AggregatedCaseTimeLogBatchUtility
 * @author Shubham Jain, Traction on Demand
 * @date 2019-07-18
 */
public with sharing class todft_AggregatedCaseTimeLogBatchUtility {

    public static Aggregation_Batch_Settings__c aggregationBatchSettings = Aggregation_Batch_Settings__c.getOrgDefaults();

    /**
	 * @description Query data from Case Time Log object
	 * @param caseTimeLogsByAggType - Time logs records
	 * @return aggregatedCaseTimeLogs - list of Aggregated_Case_Time_Log__c to upsert
	 */
    public static List<Aggregated_Case_Time_Log__c> getAggregatedCaseTimeLogs(Map<String, List<Case_Time_Log__c>> caseTimeLogsByAggType) {
        List<Aggregated_Case_Time_Log__c> aggregatedCaseTimeLogs = new List<Aggregated_Case_Time_Log__c>();
        Set<Id> caseIds;
        List<Decimal> businessHoursList;
        List<Decimal> calendarHoursList;
        Set<Id> caseTimeLogIds = new Set<Id>();

        for (String keyString : caseTimeLogsByAggType.keySet()) {
            caseIds = new Set<Id>();
            businessHoursList = new List<Decimal>();
            calendarHoursList = new List<Decimal>();
            Decimal totalBusinessHoursDuration = 0;
            Decimal totalCalHoursDuration = 0;

            //Loop over same type time log records to calculate total time duration
            for (Case_Time_Log__c thisTimeLog : caseTimeLogsByAggType.get(keyString)) {
                businessHoursList.add(thisTimeLog.Business_Hours_Duration__c);
                calendarHoursList.add(thisTimeLog.Calendar_Duration__c);
                totalBusinessHoursDuration += thisTimeLog.Business_Hours_Duration__c;
                totalCalHoursDuration += thisTimeLog.Calendar_Duration__c;
                caseTimeLogIds.add(thisTimeLog.Id);
                caseIds.add(thisTimeLog.Case__c);
            }
            businessHoursList.sort();
            calendarHoursList.sort();

            //Create new instance of Aggregated Case Time Log
            Aggregated_Case_Time_Log__c aggCsTimeLog =
                    new Aggregated_Case_Time_Log__c(Aggregation_Name__c = keyString.substringAfter('-'));
            aggCsTimeLog.Business_Hours_Duration_Sum__c = totalBusinessHoursDuration;
            aggCsTimeLog.Business_Hours_Duration_Maximum__c = businessHoursList[businessHoursList.size() - 1];
            aggCsTimeLog.Business_Hours_Duration_Minimum__c = businessHoursList[0];
            aggCsTimeLog.Number_of_Cases__c = caseIds.size();
            aggCsTimeLog.No_of_Time_Logs_Touched__c = businessHoursList.size();
            aggCsTimeLog.Calendar_Hours_Sum__c = totalCalHoursDuration;
            aggCsTimeLog.Calendar_Hours_Maximum__c = calendarHoursList[calendarHoursList.size() - 1];
            aggCsTimeLog.Calendar_Hours_Minimum__c = calendarHoursList[0];
            aggCsTimeLog.Aggregation_Start_Date__c = aggregationBatchSettings.Batch_Start_Date__c != null ? aggregationBatchSettings.Batch_Start_Date__c : null;
            aggCsTimeLog.Aggregation_End_Date__c = aggregationBatchSettings.Batch_End_Date__c != null ? aggregationBatchSettings.Batch_End_Date__c : null;
            if (keyString.substringBefore('-').equals('SS')) {
                //Populate status information
                aggCsTimeLog.Aggregation_Type__c = todft_TimeLogAggregationConstants.STATUS_STATUS_NEW;
                aggCsTimeLog.Status__c = caseTimeLogsByAggType.get(keyString)[0].Case_Status__c;
                aggCsTimeLog.Status_New__c = caseTimeLogsByAggType.get(keyString)[0].Case_Status_New__c;
                aggCsTimeLog.Case_Status_Group__c = caseTimeLogsByAggType.get(keyString)[0].Case_Status_Group__c;

            } else if (keyString.substringBefore('-').equals('OO')) {
                //Populate owner information
                aggCsTimeLog.Owner_Type__c = caseTimeLogsByAggType.get(keyString)[0].Owner_Type__c;
                aggCsTimeLog.Aggregation_Type__c = todft_TimeLogAggregationConstants.OWNER_OWNER_NEW;
                aggCsTimeLog.Parent_Owner_Text__c = caseTimeLogsByAggType.get(keyString)[0].Parent_Owner__c;
                aggCsTimeLog.Parent_Owner_New_Text__c = caseTimeLogsByAggType.get(keyString)[0].Parent_Owner_New__c;
                if (caseTimeLogsByAggType.get(keyString)[0].Parent_Owner_User__c != null) {
                    aggCsTimeLog.Parent_Owner__c = caseTimeLogsByAggType.get(keyString)[0].Parent_Owner_User__c;
                }
                if (caseTimeLogsByAggType.get(keyString)[0].Parent_Owner_User_New__c != null) {
                    aggCsTimeLog.Parent_Owner_New__c = caseTimeLogsByAggType.get(keyString)[0].Parent_Owner_User_New__c;
                }

            } else if (keyString.substringBefore('-').equals('OS')) {
                //Populate status - owner information
                aggCsTimeLog.Owner_Type__c = caseTimeLogsByAggType.get(keyString)[0].Owner_Type__c;
                aggCsTimeLog.Aggregation_Type__c = todft_TimeLogAggregationConstants.OWNER_STATUS;
                aggCsTimeLog.Status__c = caseTimeLogsByAggType.get(keyString)[0].Case_Status__c;
                aggCsTimeLog.Case_Status_Group__c = caseTimeLogsByAggType.get(keyString)[0].Case_Status_Group__c;
                aggCsTimeLog.Parent_Owner_Text__c = caseTimeLogsByAggType.get(keyString)[0].Parent_Owner__c;
                if (caseTimeLogsByAggType.get(keyString)[0].Parent_Owner_User__c != null) {
                    aggCsTimeLog.Parent_Owner__c = caseTimeLogsByAggType.get(keyString)[0].Parent_Owner_User__c;
                }
            }
            aggregatedCaseTimeLogs.add(aggCsTimeLog);
        }
        //Update processed time log records.
        if (!caseTimeLogIds.isEmpty()) {
            updateCaseTimeLogs(caseTimeLogIds);
        }
        return aggregatedCaseTimeLogs;
    }

    /**
	 * @description Updates Is_Aggregated__c true on all processed case time log records.
	 * @param caseTimeLogIds - Case Time log ids.
	 */

    public static void updateCaseTimeLogs(Set<Id> caseTimeLogIds) {
        List<Case_Time_Log__c> caseTimeLogs = new List<Case_Time_Log__c>();
        Case_Time_Log__c thisTimeLog;
        for (Id ctId : caseTimeLogIds) {
            thisTimeLog = new Case_Time_Log__c(Id = ctId);
            thisTimeLog.Is_Aggregated__c = true;
            caseTimeLogs.add(thisTimeLog);
        }
        try{
            update caseTimeLogs;
        }catch (DmlException e){
            System.debug('Unhandled exception occurred '+ e.getMessage());
        }

    }

    /**
	 * @description Updates Is_Aggregated__c true on all processed case time log records.
	 * @param totalTLogs - Count of case time logs
	 * @param totalCases - Count of cases touched
	 * @param statusCountList - List of status count
	 * @param ownerCountList - List of owner count
	 * @return newAggTimeLog - Touches aggregation record
	 */
    public static Aggregated_Case_Time_Log__c getTouchesAggregationRecord(Integer totalTLogs, Integer totalCases, List<Integer> statusCountList, List<Integer> ownerCountList) {
        Aggregated_Case_Time_Log__c newAggTimeLog = new Aggregated_Case_Time_Log__c();
        newAggTimeLog.Aggregation_Name__c = todft_TimeLogAggregationConstants.TOUCHES + System.today();
        newAggTimeLog.Aggregation_Type__c = todft_TimeLogAggregationConstants.TOUCHES;
        newAggTimeLog.No_of_Cases_Touched__c = totalCases;
        newAggTimeLog.No_of_Time_Logs_Touched__c = totalTLogs;
        newAggTimeLog.Aggregation_Start_Date__c = aggregationBatchSettings.Batch_Start_Date__c != null ? aggregationBatchSettings.Batch_Start_Date__c : null;
        newAggTimeLog.Aggregation_End_Date__c = aggregationBatchSettings.Batch_End_Date__c != null ? aggregationBatchSettings.Batch_End_Date__c : null;
        if (statusCountList.size() > 0) {
            newAggTimeLog.Time_Log_Status_Count__c = sumListElements(statusCountList);
            newAggTimeLog.Status_Count_Maximum__c = statusCountList[statusCountList.size() - 1];
            newAggTimeLog.Status_Count_Minimum__c = statusCountList[0];
        }
        if (ownerCountList.size() > 0) {
            newAggTimeLog.Time_Log_Owner_Count__c = sumListElements(ownerCountList);
            newAggTimeLog.Owner_Count_Maximum__c = ownerCountList[ownerCountList.size() - 1];
            newAggTimeLog.Owner_Count_Minimum__c = ownerCountList[0];
        }
        return newAggTimeLog;
    }

    /**
	 * @description Sum all the Integer list elements.
	 * @param lstValues - List of Integer
	 * @return sum - sum of all list elements.
	 */

    public static Integer sumListElements(List<Integer> lstValues) {
        Integer sum = 0;
        for (Integer a : lstValues) {
            sum += a;
        }
        return sum;
    }

    /**
	 * @description Returns a list of Aggregated_Case_Time_Log__c to upsert, while processing batch chunks so
	 * this method checks if record with same Aggregation Name is already inserted via this batch, if yes updates
	 * existing one else create a new record.
	 * @param newRecords - List of Integer
	 * @param insertedAggregatedTimeLogs - Map of already inserted Aggregated Case time log records.
	 * @return aggregatedCaseTimeLogsToUpsert - Returns a list of Aggregated_Case_Time_Log__c to upsert
	 */
    public static List<Aggregated_Case_Time_Log__c> updateExistingRecords(List<Aggregated_Case_Time_Log__c> newRecords, Map<String, Aggregated_Case_Time_Log__c> insertedAggregatedTimeLogs) {
        List<Aggregated_Case_Time_Log__c> aggregatedCaseTimeLogsToUpsert = new List<Aggregated_Case_Time_Log__c>();
        for (Aggregated_Case_Time_Log__c thisLog : newRecords) {
            //Check if already exist.
            if (insertedAggregatedTimeLogs.containsKey(thisLog.Aggregation_Name__c)) {
                //Check if it is Touches record.
                if (thisLog.Aggregation_Name__c.containsIgnoreCase(todft_TimeLogAggregationConstants.TOUCHES)) {
                    Aggregated_Case_Time_Log__c touchLog = insertedAggregatedTimeLogs.get(thisLog.Aggregation_Name__c);
                    touchLog.No_of_Cases_Touched__c += thisLog.No_of_Cases_Touched__c;
                    touchLog.No_of_Time_Logs_Touched__c += thisLog.No_of_Time_Logs_Touched__c;
                    touchLog.Time_Log_Status_Count__c += thisLog.Time_Log_Status_Count__c;
                    //touchLog.Time_Log_Owner_Count__c += thisLog.Time_Log_Owner_Count__c;
                    touchLog.Status_Count_Maximum__c = touchLog.Status_Count_Maximum__c > thisLog.Status_Count_Maximum__c ?
                            touchLog.Status_Count_Maximum__c : thisLog.Status_Count_Maximum__c;
                    touchLog.Status_Count_Minimum__c = touchLog.Status_Count_Minimum__c < thisLog.Status_Count_Minimum__c ?
                            touchLog.Status_Count_Minimum__c : thisLog.Status_Count_Minimum__c;
                    touchLog.Owner_Count_Maximum__c = touchLog.Owner_Count_Maximum__c > thisLog.Owner_Count_Maximum__c ?
                            touchLog.Owner_Count_Maximum__c : thisLog.Owner_Count_Maximum__c;
                    touchLog.Owner_Count_Minimum__c = touchLog.Owner_Count_Minimum__c < thisLog.Owner_Count_Minimum__c ?
                            touchLog.Owner_Count_Minimum__c : thisLog.Owner_Count_Minimum__c;
                    aggregatedCaseTimeLogsToUpsert.add(touchLog);
                } else {
                    Aggregated_Case_Time_Log__c tlog = insertedAggregatedTimeLogs.get(thisLog.Aggregation_Name__c);
                    tlog.Business_Hours_Duration_Sum__c += thisLog.Business_Hours_Duration_Sum__c;
                    tlog.Business_Hours_Duration_Minimum__c = tlog.Business_Hours_Duration_Minimum__c < thisLog.Business_Hours_Duration_Minimum__c ?
                            tlog.Business_Hours_Duration_Minimum__c : thisLog.Business_Hours_Duration_Minimum__c;
                    tlog.Business_Hours_Duration_Maximum__c = tlog.Business_Hours_Duration_Maximum__c > thisLog.Business_Hours_Duration_Maximum__c ?
                            tlog.Business_Hours_Duration_Maximum__c : thisLog.Business_Hours_Duration_Maximum__c;
                    tlog.No_of_Time_Logs_Touched__c += thisLog.No_of_Time_Logs_Touched__c;
                    tlog.Calendar_Hours_Sum__c += thisLog.Calendar_Hours_Sum__c;
                    tlog.Calendar_Hours_Minimum__c = tlog.Calendar_Hours_Minimum__c < thisLog.Calendar_Hours_Minimum__c ?
                            tlog.Calendar_Hours_Minimum__c : thisLog.Calendar_Hours_Minimum__c;
                    tlog.Calendar_Hours_Maximum__c = tlog.Calendar_Hours_Maximum__c > thisLog.Calendar_Hours_Maximum__c ?
                            tlog.Calendar_Hours_Maximum__c : thisLog.Calendar_Hours_Maximum__c;
                    tlog.Number_of_Cases__c += thisLog.Number_of_Cases__c;
                    aggregatedCaseTimeLogsToUpsert.add(tlog);
                }

            } else {
                aggregatedCaseTimeLogsToUpsert.add(thisLog);
            }
        }
        return aggregatedCaseTimeLogsToUpsert;
    }
}