objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>MHF</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
                <value>
                    <fullName>Saks</fullName>
                </value>
                <value>
                    <fullName>Off 5th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFCC_Customer_Id__c</fullName>
        <description>This field holds salesforce commerce cloud customer id. Usually case will be connected to contact but this field is to cover edge cases.</description>
        <inlineHelpText>This field holds salesforce commerce cloud customer id. Usually case will be connected to contact but this field is to cover edge cases.</inlineHelpText>
        <label>SFCC Customer Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFCC_Customer_Number__c</fullName>
        <description>This field holds commerce cloud customer number</description>
        <inlineHelpText>This field holds commerce cloud customer number</inlineHelpText>
        <label>SFCC Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Integration_Error__c.object
<CustomObject>
    <description>Stores integration errors.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The URL of the endpoint where the payload was sent</description>
        <inlineHelpText>The URL of the endpoint where the payload was sent</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>The Request of the callout if applicable</description>
        <inlineHelpText>The Request of the callout if applicable</inlineHelpText>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>The business unit of the case that the request was made on</description>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>MHF</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
                <value>
                    <fullName>Saks</fullName>
                </value>
                <value>
                    <fullName>Off 5th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShoppingCartAuraController.cls
public with sharing class ShoppingCartAuraController {

    @AuraEnabled
    public static TLAuraResponse getAgentAccessToken(String recordId)
    {
        TLAuraResponse response = new TLAuraResponse(true);
        try{
            Case aCase = getCaseById(recordId);

            if (aCase != null)
            {
                if(String.isBlank(aCase.Contact.SFCC_Customer_Id__c))
                    response.returnValuesMap.put('isBlank', true);

                SCCCommerceCloudConnect.businessUnit = aCase.Business_Unit__c;

                response = setStoreSessionURL(response);
                response = setGuestStoreFrontURL(response);

                String agentAccessToken = SCCCommerceCloudConnect.connectToCommerceCloud(aCase.Business_Unit__c);

                if ( !String.isBlank(agentAccessToken))
                {
                    response = setCustomerAuthToken(agentAccessToken, aCase, response);
                }
            }
            else if (aCase != null && aCase.ContactId != null && aCase.Contact != null)
            {
                response.returnValuesMap.put('contact', aCase.Contact);
            }
            else
            {
                response = new TLAuraResponse(false, 'No Case Found');
            }
        }
        catch(Exception e)
        {
            Integration_Error__c integrationError = trac_IntegrationError.addError(new Integration_Error__c(
                    Description__c = e.getMessage() + '\n' + e.getStackTraceString(),
                    Endpoint__c = String.valueOf(setStoreSessionURL(response).returnValuesMap.get('storeSessionURL')),
                    Request__c = '',
                    Service__c = 'Get Agent Access Token'
            ));
            insert integrationError;

            String errorMessage = trac_WS_WebServiceHelper.DEFAULT_ERROR + integrationError.Id;
            response = new TLAuraResponse(false, errorMessage);
            System.debug('Error: ' + e.getMessage() +e.getStackTraceString());
        }

        return response;
    }

    private static Case getCaseById(Id recordId) {

        List<Case> records = [
                SELECT Id, ContactId, Contact.Id, Contact.SFCC_Customer_Id__c, Contact.SFCC_Customer_Number__c, Contact.Email,
                        ContactEmail, Business_Unit__c
                FROM Case
                WHERE Id = :recordId
        ];
        return records.isEmpty() ? null : records[0];
    }

    private static TLAuraResponse setGuestStoreFrontURL(TLAuraResponse response)
    {
        String storeFrontURL = SCCCommerceCloudConnect.siteBaseUrl + '/on/demandware.store/Sites-' + SCCCommerceCloudConnect.siteId + '-Site';
        response.returnValuesMap.put('storeFrontURL', storeFrontURL);

        String guestStoreFrontURL = storeFrontURL + '/en_US/Login-Logout';
        response.returnValuesMap.put('guestStoreFrontURL', guestStoreFrontURL);

        return response;
    }

    private static TLAuraResponse setStoreSessionURL(TLAuraResponse response)
    {
        String storeSessionURL = SCCCommerceCloudConnect.siteBaseUrl + '/s/' + SCCCommerceCloudConnect.siteId + '/dw/shop/v17_4/sessions';
        response.returnValuesMap.put('storeSessionURL', storeSessionURL);
        return response;
    }

    private static TLAuraResponse setCustomerAuthToken(String agentAccessToken, Case aCase, TLAuraResponse response)
    {
        String customerAuthToken;
        if (aCase.Contact != null)
        {
            customerAuthToken = SCCCommerceCloudConnect.getCustomerAuthToken(agentAccessToken, aCase.Contact.SFCC_Customer_Id__c);
            response.returnValuesMap.put('customerAuthToken', customerAuthToken);
        }

        else {
            customerAuthToken = SCCCommerceCloudConnect.getCustomerAuthToken(agentAccessToken, null);
            response.returnValuesMap.put('customerAuthToken', customerAuthToken);
            response.returnValuesMap.put('agentAccessToken', agentAccessToken);
        }
        return response;
    }


}