objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Owner_Location__c</fullName>
        <formula>TEXT(Owner:User.Agent_Location__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Owner Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Owner_Supervisor_ID__c</fullName>
        <formula>Owner:User.ManagerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Owner Supervisor ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Power of one field for reports</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Case_Time_Log__c.object
<CustomObject>
    <description>Time Log records for the Case object. A snapshot of Case fields and time calculations when closed.</description>
    <fields>
        <fullName>Agent_Location__c</fullName>
        <description>The location of the agent working on the case</description>
        <inlineHelpText>The location of the agent working on the case</inlineHelpText>
        <label>Agent Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Jackson</fullName>
                </value>
                <value>
                    <fullName>Cebu</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Moncton</fullName>
                </value>
                <value>
                    <fullName>Manilla</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Agent_Team_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The agent on the time logs team lead</description>
        <inlineHelpText>The agents team lead</inlineHelpText>
        <label>Agent Team Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Time_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent object lookup</description>
        <inlineHelpText>This is the link up to the Case record (parent record) for this Time Log record.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Time Logs</relationshipLabel>
        <relationshipName>Case_Time_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Time Log</label>
    <nameField>
        <displayFormat>CTL-{00000}</displayFormat>
        <label>Time Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Time Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_CaseTimeLogTriggerHelper.cls
/**
 * @description Helper for trac_CaseTimeLogTrigger
 * @author      Abhishek Solanki, Traction on Demand
 * @date        2019-09-12
 */
public without sharing class trac_CaseTimeLogTriggerHelper{

    /**
    * @description Map Case's fields to Case Time Log record
    * @param       newList, list of new Case Time Log objects
    */
    public static void updateTeamLeadAndLocation(List<Case_Time_Log__c> newList){
        Set<Id> caseIdSet = new Set<Id>();
        Map<Id,Case> idVsCaseMap= new Map<Id,Case>();
        for(Case_Time_Log__c tl : newList){
            if(tl.Case__c != null)
                caseIdSet.add(tl.Case__c);
        }
        for(Case cse : [SELECT Id,Case_Owner_Supervisor_ID__c,Case_Owner_Location__c FROM Case WHERE Id IN :caseIdSet]){
            idVsCaseMap.put(cse.Id,cse);
        }
        for(Case_Time_Log__c tl : newList){
            if(tl.Case__c != null){
                tl.Agent_Team_Lead__c = idVsCaseMap.get(tl.Case__c).Case_Owner_Supervisor_ID__c;
                tl.Agent_Location__c = idVsCaseMap.get(tl.Case__c).Case_Owner_Location__c;
            }
        }
    }
}