objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Power of one field for reports</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Promo_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Stamped when promo code is associated to the case. Added to the case close email</description>
        <label>Promo Code</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Promo_Code__c.object
<CustomObject>
    <fields>
        <fullName>Amount_List__c</fullName>
        <label>Amount</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$5.00</fullName>
                </value>
                <value>
                    <fullName>5%</fullName>
                </value>
                <value>
                    <fullName>$10.00</fullName>
                </value>
                <value>
                    <fullName>10%</fullName>
                </value>
                <value>
                    <fullName>$15.00</fullName>
                </value>
                <value>
                    <fullName>15%</fullName>
                </value>
                <value>
                    <fullName>$20.00</fullName>
                </value>
                <value>
                    <fullName>20%</fullName>
                </value>
                <value>
                    <fullName>$25.00</fullName>
                </value>
                <value>
                    <fullName>25%</fullName>
                </value>
                <value>
                    <fullName>$30.00</fullName>
                </value>
                <value>
                    <fullName>30%</fullName>
                </value>
                <value>
                    <fullName>$35.00</fullName>
                </value>
                <value>
                    <fullName>35%</fullName>
                </value>
                <value>
                    <fullName>$40.00</fullName>
                </value>
                <value>
                    <fullName>40%</fullName>
                </value>
                <value>
                    <fullName>45.00$</fullName>
                </value>
                <value>
                    <fullName>45%</fullName>
                </value>
                <value>
                    <fullName>$50.00</fullName>
                </value>
                <value>
                    <fullName>50%</fullName>
                </value>
                <value>
                    <fullName>$55.00</fullName>
                </value>
                <value>
                    <fullName>55%</fullName>
                </value>
                <value>
                    <fullName>$60.00</fullName>
                </value>
                <value>
                    <fullName>60%</fullName>
                </value>
                <value>
                    <fullName>$65.00</fullName>
                </value>
                <value>
                    <fullName>65%</fullName>
                </value>
                <value>
                    <fullName>$70.00</fullName>
                </value>
                <value>
                    <fullName>70%</fullName>
                </value>
                <value>
                    <fullName>$75.00</fullName>
                </value>
                <value>
                    <fullName>75%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Promo Codes</relationshipLabel>
        <relationshipName>Promo_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Promo Code</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Promo Code</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promo Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_PromoCodeSearchControllerTest.cls
/**
 * @name trac_PromoCodeSearchControllerTest
 * @author Daniel Labonte, Traction on Demand
 * @date 2019-07-04
 * @description unit tests for the promo code search apex controller
 */

@IsTest
private class trac_PromoCodeSearchControllerTest {
    static final Integer PROMO_CODES_CONSUME = 2;
    static String AMOUNT_LIST_PICKLIST_VALUE;

    @TestSetup
    static void setup() {
        List<String> pickListValuesList = new List<String>();
        for (Schema.PicklistEntry pickListVal : Promo_Code__c.Amount_List__c.getDescribe().getPicklistValues()){
            pickListValuesList.add(pickListVal.getLabel());
        }
        Double randomNumber = Math.random();
        Integer arraySize = pickListValuesList.size();
        Integer randomIndex = (randomNumber * (arraySize - 1)).intValue();
        for (String selectedValue : pickListValuesList) {
            if (randomIndex == 0) {
                AMOUNT_LIST_PICKLIST_VALUE = selectedValue;
                break;
            }
            randomIndex--;
        }
    }

    @IsTest
    static void testGetCurrentCasePromoCode() {
        final Integer COUNT = 6;
        TLTestFactory factory = new TLTestFactory();
        Case cs = (Case)factory.createSObject(new Case(),true);
        factory.createSObjects(new Promo_Code__c(Amount_List__c=AMOUNT_LIST_PICKLIST_VALUE,Case__c=cs.Id), COUNT, true);

        Test.startTest();
        Integer promoCodeCount = trac_PromoCodeSearchController.getCurrentCasePromoCode(cs.Id);
        Test.stopTest();

        System.assertEquals(COUNT,promoCodeCount,'The number of promo codes found was not the amount expected.');
    }

    @IsTest
    static void testGetPromoCodes() {
        TLTestFactory factory = new TLTestFactory();
        factory.createSObject(new Promo_Code__c(Amount_List__c=AMOUNT_LIST_PICKLIST_VALUE), true);

        Case cs = (Case)factory.createSObject(new Case(),true);

        Object testResult;
        Test.startTest();
        testResult = trac_PromoCodeSearchController.applyPromoCode(AMOUNT_LIST_PICKLIST_VALUE, cs.Id);
        Test.stopTest();

        System.assert(testResult != null, 'No promo codes were retrieved');
    }
}