objects/Case.object
<CustomObject>
    <fields>
        <fullName>Promo_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Stamped when promo code is associated to the case. Added to the case close email</description>
        <label>Promo Code</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Promo_Code__c.object
<CustomObject>
    <fields>
        <fullName>Amount_List__c</fullName>
        <label>Amount</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$5.00</fullName>
                </value>
                <value>
                    <fullName>5%</fullName>
                </value>
                <value>
                    <fullName>$10.00</fullName>
                </value>
                <value>
                    <fullName>10%</fullName>
                </value>
                <value>
                    <fullName>$15.00</fullName>
                </value>
                <value>
                    <fullName>15%</fullName>
                </value>
                <value>
                    <fullName>$20.00</fullName>
                </value>
                <value>
                    <fullName>20%</fullName>
                </value>
                <value>
                    <fullName>$25.00</fullName>
                </value>
                <value>
                    <fullName>25%</fullName>
                </value>
                <value>
                    <fullName>$30.00</fullName>
                </value>
                <value>
                    <fullName>30%</fullName>
                </value>
                <value>
                    <fullName>$35.00</fullName>
                </value>
                <value>
                    <fullName>35%</fullName>
                </value>
                <value>
                    <fullName>$40.00</fullName>
                </value>
                <value>
                    <fullName>40%</fullName>
                </value>
                <value>
                    <fullName>45.00$</fullName>
                </value>
                <value>
                    <fullName>45%</fullName>
                </value>
                <value>
                    <fullName>$50.00</fullName>
                </value>
                <value>
                    <fullName>50%</fullName>
                </value>
                <value>
                    <fullName>$55.00</fullName>
                </value>
                <value>
                    <fullName>55%</fullName>
                </value>
                <value>
                    <fullName>$60.00</fullName>
                </value>
                <value>
                    <fullName>60%</fullName>
                </value>
                <value>
                    <fullName>$65.00</fullName>
                </value>
                <value>
                    <fullName>65%</fullName>
                </value>
                <value>
                    <fullName>$70.00</fullName>
                </value>
                <value>
                    <fullName>70%</fullName>
                </value>
                <value>
                    <fullName>$75.00</fullName>
                </value>
                <value>
                    <fullName>75%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consumed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consumed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Promo_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Promo Code</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Promo Code</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promo Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_GetPromoCodeTest.cls
/**
* Test Class for trac_GetPromoCode
*  
* @author Piyush Bansal, Traction on Demand
* @date 2020-01-15
* @group GetPromoCode
*/

@IsTest
public class trac_GetPromoCodeTest {
    
    //Test case of method GetPromoCode() to fetch the promocodes list
    @IsTest
    static void testGetPromoCode() {
        final Integer COUNT = 6;
        TLTestFactory factory = new TLTestFactory();
        factory.createSObjects(new Promo_Code__c(Consumed__c = false, Amount_List__c='$5.00'), COUNT, true);
        
        Test.startTest();
        List<Promo_Code__c> promoCodeList = (List<Promo_Code__c>)trac_GetPromoCode.getPromoCode('$5.00');
        Test.stopTest();
        
        System.assertEquals(COUNT,promoCodeList.size());
    }
    //Test case of method ConsumePromoCodes()
    @IsTest
    static void testConsumePromoCodes(){
        final Integer COUNT = 6;
        TLTestFactory factory = new TLTestFactory();
        Case cs = (Case)factory.createSObject(new Case(), true);
        List<Promo_Code__c>promoCodeList=factory.createSObjects(new Promo_Code__c(Consumed__c = false, Amount_List__c='$5.00'), COUNT, true);
        
        
        Map<String,String> promoCodesMap = new Map<String,String>();
        for(Promo_Code__c promoCode:promoCodeList){
            promoCodesMap.put(promoCode.Id,promoCode.Promo_Code__c);
            
        }
        Test.startTest();
        Boolean result = trac_GetPromoCode.consumePromoCodes(promoCodesMap,cs.Id);
        Test.stopTest();  
        System.assertEquals(result, false);
        
    }
    //Test case of method ConsumePromoCodes() in case exception is thrown
    @IsTest
    static void testConsumePromoCodesThrowException(){
        Map<String,String> promoCodesMap = new Map<String,String>();
        Boolean result = false;
        TLTestFactory factory = new TLTestFactory();
        try{
            Case cs = (Case)factory.createSObject(new Case(), true);
            Test.startTest();
            result=trac_GetPromoCode.consumePromoCodes(null,cs.Id);
            Test.stopTest(); 
        }
        catch(Exception e){
            System.assertEquals(result, false,'Exception thrown in method of consumePromoCodes()');
        }
        
    }
}