objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>MHF</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
                <value>
                    <fullName>Saks</fullName>
                </value>
                <value>
                    <fullName>Off 5th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Urgent_Message__c.object
<CustomObject>
    <fields>
        <fullName>Activation_Date__c</fullName>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Banner__c</fullName>
        <label>Banner</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
                <value>
                    <fullName>MHF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <label>Urgent Message</label>
    <nameField>
        <label>Urgent Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Urgent Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_UrgentMessageCtlrTest.cls
/**
 *  @description Test Class for trac_UrgentMessageCtlr
 *  @author 	 Jeremy Horan, Traction on Demand.
 *  @date        2016-10-18
 */
@isTest
private class trac_UrgentMessageCtlrTest {

    static final TLTestFactory factory = new TLTestFactory();
	
	@isTest static void test_controller() {

        String testBusinessUnit = 'Hudson\'s Bay';

        Case testCase = (Case) factory.createSObject(new Case(
                Business_Unit__c = testBusinessUnit
        ), true);

		Urgent_Message__c urgentMessage = new Urgent_Message__c(
			Activation_Date__c = Date.today(),
			Body__c = 'TEST',
			Expiration_Date__c = Date.today().addDays(3),
            Banner__c = testBusinessUnit
		);
		insert urgentMessage;

		System.assertEquals(1, trac_UrgentMessageCtlr.getUrgentMessages(testCase.Id).size());
		System.assertNotEquals(null,trac_UrgentMessageCtlr.getUrgentMessage(urgentMessage.Id));
	}	
}