objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>MHF</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
                <value>
                    <fullName>Saks</fullName>
                </value>
                <value>
                    <fullName>Off 5th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_is_Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox that indicates if an order was cancelled during the case. The statement will evaluate true based on the Cancel order action.</description>
        <inlineHelpText>Checkbox that indicates if an order was cancelled during the case. The statement will evaluate true based on the Cancel order action.</inlineHelpText>
        <label>Order is Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Integration_Error__c.object
<CustomObject>
    <description>Stores integration errors.</description>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_CancelOrderCltrTest.cls
/**
 * Created by nrodrigues on 4/28/2020.
 */

@IsTest
private class trac_CancelOrderCltrTest {

    static final TLTestFactory factory = new TLTestFactory();

    @IsTest
    static void testCancelOrder() {

        Case testCase = (Case) factory.createSObject(new Case(Subject = 'Test Case', Status = 'New', Order_Number__c='12345') ,true );

        Test.setMock(HttpCalloutMock.class, new MockOrderResponses('/cancel'));
        TLAuraResponse response  = trac_CancelOrderCtlr.cancelOrder(testCase,testCase.Business_Unit__c, testCase.Order_Number__c, '123','','Customer Preference','HBC_MC_CC_002', '1');
        System.assertEquals(true, response.isSuccess);

        testCase = [SELECT Id,Order_is_Cancelled__c, Cancellation_Reason__c FROM Case WHERE Subject='Test Case' LIMIT 1];
        System.assertEquals(true, testCase.Order_is_Cancelled__c);
        System.assertEquals('Customer Preference', testCase.Cancellation_Reason__c);


    }

    @IsTest
    static void testCancelOrderError() {

        Case testCase = (Case) factory.createSObject(new Case(Subject = 'Test Case', Status = 'New', Order_Number__c='12345', Cancellation_Reason__c='Customer Preference') ,true );

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockOrderResponsesError('/cancel'));
        TLAuraResponse response  = trac_CancelOrderCtlr.cancelOrder(testCase,testCase.Business_Unit__c, testCase.Order_Number__c, '123','','Test','HBC_MC_CC_002', '1');
        Test.stopTest();

        System.assertEquals(false, response.isSuccess);
        Integration_Error__c error = [SELECT Id, Service__c FROM Integration_Error__c LIMIT 1];
        System.assertEquals('Cancel Order', error.Service__c);
    }
}