objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Power of one field for reports</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Order_Refund_Credit__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case associated to the ORC</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Refunds/Credits</relationshipLabel>
        <relationshipName>Order_Refunds_Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ORC_Status__c</fullName>
        <label>ORC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Requires Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Refund/Credit</label>
    <nameField>
        <displayFormat>ORC-{0000000}</displayFormat>
        <label>Order Refund/Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Refunds/Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/trac_OrderRefundCreditCleanupBatchTest.cls
/**
 * Created by jhoran on 9/10/2019.
 */

@IsTest
private class trac_OrderRefundCreditCleanupBatchTest {

    static final TLTestFactory factory = new TLTestFactory();

    @IsTest
    static void testBatch() {
        Case parentCase = (Case) factory.createSObject(new Case(Status = trac_CaseConstants.STATUS_CLOSED), true);

        Order_Refund_Credit__c orderRefundCredit = (Order_Refund_Credit__c) factory.createSObject(new Order_Refund_Credit__c(
                Case__c = parentCase.Id,
                ORC_Status__c = trac_OrderRefundCreditConstants.STATUS_DRAFT
        ), true);

        Test.startTest();
        Database.executeBatch(new trac_OrderRefundCreditCleanupBatch(), 200);
        Test.stopTest();

        Order_Refund_Credit__c queriedOrderRefundCredit = [SELECT Id, ORC_Status__c FROM Order_Refund_Credit__c WHERE Id = :orderRefundCredit.Id];

        System.assertEquals(trac_OrderRefundCreditConstants.STATUS_CANCELLED, queriedOrderRefundCredit.ORC_Status__c, 'ORC should be closed by batch');
    }

    @IsTest
    static void testScheduler() {
        String CRON_EXP = '0 0 0 19 6 ? 2099';

        Test.startTest();
        trac_OrderRefundCreditCleanupBatch orderRefundCreditCleanupBatch = new trac_OrderRefundCreditCleanupBatch();
        String jobId = System.schedule('TestOrderRefundCreditCleanupBatch', CRON_EXP, orderRefundCreditCleanupBatch);
        Test.stopTest();

        System.assert(jobId != null);
    }
}