objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Power of one field for reports</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_ORC_Open__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checks if any of the attached ORCs are open.</description>
        <label>Is ORC Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trigger_Approval_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in Case Status update trigger to bypass validation rule due to roll ups being after triggers in order of execution.</description>
        <label>Trigger Approval Override</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Order_Refund_Credit__c.object
<CustomObject>
    <fields>
        <fullName>Amount_to_Refund__c</fullName>
        <formula>if(OR(ispickval( Reason__c , &quot;Order Not Received&quot;)=TRUE, Quantity__c = Quantity_Not_Received__c ), Amount_Charged__c,Amount_Charged__c - Adjusted_Price__c) + if( Credit_Shipping_Fee__c =TRUE, Shipping_Fee__c ,0)+Other_Refund__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ORC Amount to Refund</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <formula>( Amount_to_Refund__c &gt;= 100 ||  Replacement_Gift_Card_Amount__c &gt;=100 || ISPICKVAL(Gift_Card_Amount__c, &quot;100&quot;) ) 
&amp;&amp; 

NOT(ISPICKVAL(ORC_Status__c, &apos;Approved&apos;) || ISPICKVAL(ORC_Status__c, &apos;Closed&apos;) || ISPICKVAL(ORC_Status__c, &apos;Cancelled&apos;) || ISPICKVAL(ORC_Status__c, &apos;Draft&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who approved the ORC</description>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Order_Refunds_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case associated to the ORC</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Refunds/Credits</relationshipLabel>
        <relationshipName>Order_Refunds_Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ORC_Status__c</fullName>
        <label>ORC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Requires Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Number__c</fullName>
        <label>Transaction Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Order Refund/Credit</label>
    <nameField>
        <displayFormat>ORC-{0000000}</displayFormat>
        <label>Order Refund/Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Refunds/Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Refund_Credit_Case_Status_Setting__mdt.object
<CustomObject>
    <description>Configuration for which Case statuses will handle which actions on Order Refund Credit</description>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Should this process run?</description>
        <inlineHelpText>Should this process run?</inlineHelpText>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <defaultValue>&quot;Case&quot;</defaultValue>
        <description>The Object the process is running on</description>
        <inlineHelpText>The Object the Process is running on</inlineHelpText>
        <label>Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                    <default>true</default>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>Order Refund Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>The apex process that will be run</description>
        <inlineHelpText>The apex process that will be run</inlineHelpText>
        <label>Process</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Set ORC Approval Status</fullName>
                    <default>true</default>
                    <label>Set ORC Approval Status</label>
                </value>
                <value>
                    <fullName>Set Case Status</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The Status of the Record</description>
        <inlineHelpText>The Status of the Record</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Order Refund Credit Case Status Setting</label>
    <pluralLabel>Order Refund Credit Case Status Settings</pluralLabel>
</CustomObject>

classes/trac_OrderRefundCreditHelper.cls
/**
 *  @description Order Refund Credit Trigger Handler, contains methods called by the ORC trigger
 *  @author      Jeremy Horan, Traction on Demand.
 *  @date        8/9/2019
 */
public without sharing class trac_OrderRefundCreditHelper {

    /**
     * @description Flag case if the ORCs are open
     * @param       newOrderRefundCredits, List of new ORC records
     *              oldOrderRefundCreditsByIds, Map of Id vs old ORC records
     * @return      void
     */
    public static void flagCaseIfOpenORC(List<Order_Refund_Credit__c> newOrderRefundCredits, Map<Id, Order_Refund_Credit__c> oldOrderRefundCreditsByIds){
        List<Case> casesToUpdate = new List<Case>();
        try{
            for(Order_Refund_Credit__c orderRefundCredit : newOrderRefundCredits){
                if(String.isNotBlank(orderRefundCredit.ORC_Status__c) && (oldOrderRefundCreditsByIds.isEmpty() || orderRefundCredit.ORC_Status__c != oldOrderRefundCreditsByIds.get(orderRefundCredit.Id).ORC_Status__c)){
                    Case cse = new Case();
                    cse.Id = orderRefundCredit.Case__c;
                    if(orderRefundCredit.ORC_Status__c.equals(trac_OrderRefundCreditConstants.STATUS_REQUIRES_APPROVAL) ||
                                    orderRefundCredit.ORC_Status__c.equals(trac_OrderRefundCreditConstants.STATUS_APPROVED) ||
                                    orderRefundCredit.ORC_Status__c.equals(trac_OrderRefundCreditConstants.STATUS_NEW) ||
                                    orderRefundCredit.ORC_Status__c.equals(trac_OrderRefundCreditConstants.STATUS_IN_PROGRESS))
                    {
                        cse.Is_ORC_Open__c = true;
                    }else{
                        cse.Is_ORC_Open__c = false;
                    }
                    casesToUpdate.add(cse);
                }
            }

            if(casesToUpdate!=null && !casesToUpdate.isEmpty()){
                update casesToUpdate;
            }
        }catch(Exception err){
            System.debug(err.getMessage() + '\n' + err.getStackTraceString());
        }
    }

    /**
     * @description Close Case Based on ORC being Closed
     * @param       newOrderRefundCredits, List of new ORC records
     *              oldOrderRefundCreditsByIds, Map of Id vs old ORC records
     * @return      void
     */
    public static void closeCase(List<Order_Refund_Credit__c> newOrderRefundCredits, Map<Id, Order_Refund_Credit__c> oldOrderRefundCreditsByIds){
        Set<Id> caseIdSet = new Set<Id>();
        List<Case> casesToClose = new List<Case>();
        List<String> orcStatusList = new List<String>{trac_OrderRefundCreditConstants.STATUS_REQUIRES_APPROVAL, trac_OrderRefundCreditConstants.STATUS_DECLINED, trac_OrderRefundCreditConstants.STATUS_DRAFT};
        try{
            for(Order_Refund_Credit__c orderRefundCredit : newOrderRefundCredits){
                if(String.isNotBlank(orderRefundCredit.ORC_Status__c) && orderRefundCredit.ORC_Status__c.equals(trac_OrderRefundCreditConstants.STATUS_CLOSED) && (oldOrderRefundCreditsByIds.isEmpty() || orderRefundCredit.ORC_Status__c != oldOrderRefundCreditsByIds.get(orderRefundCredit.Id).ORC_Status__c)){
                    caseIdSet.add(orderRefundCredit.Case__c);
                }
            }
            for(Order_Refund_Credit__c orc : [SELECT Id,ORC_Status__c,Case__c FROM Order_Refund_Credit__c WHERE ORC_Status__c NOT IN : orcStatusList AND Case__c IN :caseIdSet]){
                if(String.isNotBlank(orc.ORC_Status__c) && !orc.ORC_Status__c.equals(trac_OrderRefundCreditConstants.STATUS_CLOSED)){
                    caseIdSet.remove(orc.Case__c);
                }
            }
            for(Id caseId : caseIdSet){
                Case caseRec = new Case();
                caseRec.Id = caseId;
                caseRec.Status = trac_CaseConstants.STATUS_CLOSED;
                casesToClose.add(caseRec);
            }

            if(casesToClose!=null && !casesToClose.isEmpty()){
                update casesToClose;
            }
    }catch(Exception err){
            System.debug(err.getMessage() + '\n' + err.getStackTraceString());
        }
    }

    /**
     * @description Post comment on parent case with Transaction number
     * @param       newOrderRefundCreditsByIds, Map of Id vs new ORC records
     * @return      void
     */
    public static void postOnParentCase(Map<Id, Order_Refund_Credit__c> newOrderRefundCreditsByIds, Map<Id, Order_Refund_Credit__c> oldOrderRefundCreditsByIds){
        List<FeedItem> feedItems = new List<FeedItem>();
        try{
            for(Id orcId : newOrderRefundCreditsByIds.keySet()){
                if(!TLTrigger.wasRecordProcessed(orcId, 'postOnParentCase')){
                    if(String.isNotBlank(newOrderRefundCreditsByIds.get(orcId).ORC_Status__c) && newOrderRefundCreditsByIds.get(orcId).ORC_Status__c.equals(trac_OrderRefundCreditConstants.STATUS_CLOSED) && String.isNotBlank(newOrderRefundCreditsByIds.get(orcId).Transaction_Number__c) && (newOrderRefundCreditsByIds.get(orcId).ORC_Status__c != oldOrderRefundCreditsByIds.get(orcId).ORC_Status__c || newOrderRefundCreditsByIds.get(orcId).Transaction_Number__c!= oldOrderRefundCreditsByIds.get(orcId).Transaction_Number__c)){
                        String bodyFromLabel = Label.Refund_Processed;
                        bodyFromLabel = bodyFromLabel.replace('{Name}', newOrderRefundCreditsByIds.get(orcId).Name);
                        bodyFromLabel = bodyFromLabel.replace('{Transaction_Number__c}', newOrderRefundCreditsByIds.get(orcId).Transaction_Number__c);
                        bodyFromLabel = bodyFromLabel.replace('{Amount_to_Refund__c}', String.valueOf(newOrderRefundCreditsByIds.get(orcId).Amount_to_Refund__c));
                        FeedItem post = new FeedItem();
                        post.ParentId = newOrderRefundCreditsByIds.get(orcId).Case__c;
                        post.Body = bodyFromLabel;
                        feedItems.add(post);
                        TLTrigger.addRecordProcess(orcId, 'postOnParentCase');
                    }
                }
            }

            if(feedItems!=null && !feedItems.isEmpty()){
                insert feedItems;
            }
        }catch(Exception err){
            System.debug(err.getMessage() + '\n' + err.getStackTraceString());
        }
    }


    public static void setCaseStatus(List<Order_Refund_Credit__c> newOrderRefundCredits, Map<Id, Order_Refund_Credit__c> oldOrderRefundCreditsByIds) {
        Map<String, Set<Id>> caseIdsByStatus = new Map<String, Set<Id>>();

        for (Order_Refund_Credit__c newOrderRefundCredit : newOrderRefundCredits) {
            if (!TLTrigger.wasRecordProcessed(newOrderRefundCredit.Id, 'setCaseStatus')) {

                Order_Refund_Credit__c oldOrderRefundCredit;
                if (oldOrderRefundCreditsByIds.containsKey(newOrderRefundCredit.Id)) {
                    oldOrderRefundCredit = oldOrderRefundCreditsByIds.get(newOrderRefundCredit.Id);
                }

                if (newOrderRefundCredit.Case__c != null && (oldOrderRefundCredit == null || oldOrderRefundCredit.ORC_Status__c != newOrderRefundCredit.ORC_Status__c)) {
                    if (!caseIdsByStatus.containsKey(newOrderRefundCredit.ORC_Status__c)) {
                        caseIdsByStatus.put(newOrderRefundCredit.ORC_Status__c, new Set<Id>());
                    }
                    caseIdsByStatus.get(newOrderRefundCredit.ORC_Status__c).add(newOrderRefundCredit.Case__c);
                }
            }
        }

        if (!caseIdsByStatus.isEmpty()) {
            filterAndUpdateCases(caseIdsByStatus);
        }
    }

    public static void setApprovedBy(List<Order_Refund_Credit__c> newOrderRefundCredits, Map<Id, Order_Refund_Credit__c> oldOrderRefundCreditsByIds) {
        for (Order_Refund_Credit__c newOrderRefundCredit : newOrderRefundCredits) {

            Order_Refund_Credit__c oldOrderRefundCredit;
            if (oldOrderRefundCreditsByIds.containsKey(newOrderRefundCredit.Id)) {
                oldOrderRefundCredit = oldOrderRefundCreditsByIds.get(newOrderRefundCredit.Id);
            }

            if (newOrderRefundCredit.ORC_Status__c == trac_OrderRefundCreditConstants.STATUS_APPROVED && (oldOrderRefundCredit == null || oldOrderRefundCredit.ORC_Status__c != newOrderRefundCredit.ORC_Status__c)) {
                newOrderRefundCredit.Approved_By__c = UserInfo.getUserId();
            }
        }
    }

    private static void filterAndUpdateCases(Map<String, Set<Id>> caseIdsByStatus) {
        List<Case> casesToUpdate = new List<Case>();

        if (!caseIdsByStatus.isEmpty()) {
            Set<Id> caseIdsToQuery = new Set<Id>();
            List<Order_Refund_Credit_Case_Status_Setting__mdt> orderRefundCreditCaseStatusSettings = getOrderRefundCreditCaseStatusSettingsByStatus(caseIdsByStatus.keySet(), 'Set Case Status');

            for (Order_Refund_Credit_Case_Status_Setting__mdt orderRefundCreditCaseStatusSetting : orderRefundCreditCaseStatusSettings) {
                if (caseIdsByStatus.containsKey(orderRefundCreditCaseStatusSetting.Status__c)) {
                    caseIdsToQuery.addAll(caseIdsByStatus.get(orderRefundCreditCaseStatusSetting.Status__c));
                }
            }

            if (!caseIdsToQuery.isEmpty()) {
                Map<Id, List<Order_Refund_Credit__c>> orderRefundCreditsByCaseIds = new Map<Id, List<Order_Refund_Credit__c>>();
                List<Order_Refund_Credit__c> orderRefundCredits = getOrderRefundCreditsByCaseIds(caseIdsToQuery);

                for (Order_Refund_Credit__c orderRefundCredit : orderRefundCredits) {
                    if (!orderRefundCreditsByCaseIds.containsKey(orderRefundCredit.Case__c)) {
                        orderRefundCreditsByCaseIds.put(orderRefundCredit.Case__c, new List<Order_Refund_Credit__c>());
                    }
                    orderRefundCreditsByCaseIds.get(orderRefundCredit.Case__c).add(orderRefundCredit);
                }

                for (Id caseId : orderRefundCreditsByCaseIds.keySet()) {
                    String caseStatus = getStatusFromOrderRefundCredits(orderRefundCreditsByCaseIds.get(caseId));
                    if (caseStatus != null) {
                        Case caseToUpdate = new Case(Id = caseId, Status = caseStatus);

                        caseToUpdate.Trigger_Approval_Override__c = caseStatus == trac_CaseConstants.STATUS_POS_TEAM;

                        casesToUpdate.add(caseToUpdate);
                        TLTrigger.addRecordProcess(caseId, 'setCaseStatus');
                    }
                }
            }
        }

        if (!casesToUpdate.isEmpty()) {
            update casesToUpdate;
        }
    }

    private static String getStatusFromOrderRefundCredits(List<Order_Refund_Credit__c> orderRefundCredits) {
        String status;

        Boolean hasNoDeclinedStatuses = true;
        for (Order_Refund_Credit__c orderRefundCredit : orderRefundCredits) {
            if (orderRefundCredit.ORC_Status__c == trac_OrderRefundCreditConstants.STATUS_DECLINED) {
                hasNoDeclinedStatuses = false;
                break;
            }
        }

        status = (hasNoDeclinedStatuses) ? trac_CaseConstants.STATUS_POS_TEAM : trac_CaseConstants.STATUS_TEAM_ASSISTANCE_NEEDED;

        return status;
    }

    private static List<Order_Refund_Credit_Case_Status_Setting__mdt> getOrderRefundCreditCaseStatusSettingsByStatus(Set<String> orderRefundCreditStatuses, String process) {
        List<Order_Refund_Credit_Case_Status_Setting__mdt> orderRefundCreditCaseStatusSettings = [
                SELECT Id, Status__c
                FROM Order_Refund_Credit_Case_Status_Setting__mdt
                WHERE Enabled__c = true AND Object__c = 'Order Refund Credit' AND Status__c IN :orderRefundCreditStatuses AND Process__c = :process
        ];
        return orderRefundCreditCaseStatusSettings;
    }

    private static List<Order_Refund_Credit__c> getOrderRefundCreditsByCaseIds(Set<Id> caseIds) {
        List<Order_Refund_Credit__c> orderRefundCreditCaseStatusSettings = [
                SELECT Id, Case__c, ORC_Status__c, Approval_Required__c
                FROM Order_Refund_Credit__c
                WHERE Case__c IN :caseIds
        ];
        return orderRefundCreditCaseStatusSettings;
    }
}