objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Age_In_Business_Hours__c</fullName>
        <description>Used as part of the case age in business hours package. The total case age in business hours from open to close. Updated on case status change</description>
        <inlineHelpText>The total case age in business hours from open to close.</inlineHelpText>
        <label>Case Age In Business Hours</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Status_Change__c</fullName>
        <description>Stores the last time the status changed -- used by the Case Business Hours Tools package.</description>
        <label>Last Status Change</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_With_Customer__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The time in business hours that this case spent in the hands of the customer. Part of time in business hours package</description>
        <inlineHelpText>The time in business hours that this case spent in the hands of the customer.</inlineHelpText>
        <label>Time With Customer</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_With_Support__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The time in business hours that this case spent with support.</description>
        <inlineHelpText>The time in business hours that this case spent with support.</inlineHelpText>
        <label>Time With Support</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Stop_Status__c.object
<CustomObject>
    <description>A case status in which the &quot;clock should stop,&quot; i.e. time calculated in business hours should not be added to the &quot;Time With Support&quot; field.</description>
    <label>Stop Status</label>
    <nameField>
        <label>Stop Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stop Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CalculateBusinessHoursAgesTest.cls
@isTest
private class CalculateBusinessHoursAgesTest {
    private static testMethod void testBusinessHoursBucketer() {
        Stop_Status__c ss = new Stop_Status__c(Name = trac_CaseConstants.STATUS_AWAITING_CUSTOMER);
        insert ss;

        Case c = new Case();
        c.Status = 'New';
        c.Last_Status_Change__c = System.now();
        insert c;

        c.Status = trac_CaseConstants.STATUS_AWAITING_CUSTOMER;
        update c;

        c.Status = 'New';
        update c;

		Case updatedCase = [SELECT Time_With_Customer__c,Time_With_Support__c,Case_Age_In_Business_Hours__c FROM Case WHERE Id=:c.Id];
		System.assert(updatedCase.Time_With_Customer__c!=null);
        System.assert(updatedCase.Time_With_Support__c!=null);
        System.assert(updatedCase.Case_Age_In_Business_Hours__c==null);

        c.Status = 'Closed';
        update c;

        updatedCase = [SELECT Time_With_Customer__c,Time_With_Support__c,Case_Age_In_Business_Hours__c FROM Case WHERE Id=:c.Id];

        System.assert(updatedCase.Time_With_Customer__c!=null);
        System.assert(updatedCase.Time_With_Support__c!=null);
        System.assert(updatedCase.Case_Age_In_Business_Hours__c!=null);
    }
}