objects/Case.object
<CustomObject>
    <fields>
        <fullName>Executive_Escalation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Email of the contact on the case when an executive escalation case is created.</description>
        <label>Executive Escalation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Previous_Queue_Owner_ID__c</fullName>
        <description>Prints the ID of the last Queue to own this record. Used to send cases on hold back to previous queue.</description>
        <label>Previous Queue Owner ID</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/trac_CaseReassignmentBatch.cls
/**
 * @description Batch class to reassign cases to back to the “Action Required”  queue
 * @author      Rajat Agrawal, Traction on Demand
 * @date        2019-06-10
 */
global class trac_CaseReassignmentBatch implements Database.Batchable<sObject>, Schedulable {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Id, OwnerId, Status, Previous_Queue_Owner_ID__c, IsClosed, Executive_Escalation__c FROM Case WHERE ClosedDate = null AND Previous_Queue_Owner_ID__c != null');
    }

    global void execute(Database.BatchableContext BC, List<Case> scope) {
        trac_CaseReassignmentBatchHelper.reassignCases(scope);
    }

    global void finish(Database.BatchableContext BC) {}

    //Schedule batch job
    global void execute(SchedulableContext ctx) {
        Database.executeBatch(new trac_CaseReassignmentBatch(), 200);
    }

}