objects/Case.object
<CustomObject>
    <fields>
        <fullName>Don_t_Send_Auto_Response__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use in case loop prevention. Sets to true when auto response is sent the first time</description>
        <label>Don&apos;t Send Auto Response</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Email_To_Case_Loop_Prevent__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Interval__c</fullName>
        <label>Interval</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Email To Case Loop Prevent</label>
</CustomObject>

classes/trac_EmailToCaseLoopPrevent.cls
/**
*	trac_EmailToCaseLoopPrevent
*	@description Prevent Email To Case Loop
*	@author Kofi Johnson, Traction on Demand
*/
public class trac_EmailToCaseLoopPrevent {
	private final static Integer HOURS_IN_DAY = 24;
	private final static Integer MINUTES_IN_HOUR = 60;
	private final static Integer DEFAULT_TIME_INTERVAL = HOURS_IN_DAY * MINUTES_IN_HOUR;
	
	public static void checkEmailToCaseLoop(List<Case> newCases) {
 
		Integer interval = DEFAULT_TIME_INTERVAL; 

		Email_To_Case_Loop_Prevent__c loopPreventCustomSetting = Email_To_Case_Loop_Prevent__c.getOrgDefaults();
		if(loopPreventCustomSetting != null && loopPreventCustomSetting.Interval__c != null) {
		   interval = Integer.valueOf(loopPreventCustomSetting.Interval__c);
		}

		Map<String, Case> emailToCases = new Map<String, Case>();

		for(Case aCase :newCases) {
		    if (String.isBlank(aCase.SuppliedEmail) == false && aCase.Origin != null && aCase.Origin.containsIgnoreCase('EMAIL')) {
		    	emailToCases.put(aCase.SuppliedEmail, aCase);
		    }
		}

		preventLoopCases(emailToCases, interval);
    }

    private static void preventLoopCases(Map<String,Case> emailToCases, Integer interval) {
		List<Case> originalCases = [SELECT SuppliedEmail FROM Case WHERE CreatedDate <= :Datetime.now() AND CreatedDate >= :Datetime.now().addMinutes(-interval) AND SuppliedEmail IN :emailToCases.keySet() AND Don_t_Send_Auto_Response__c != true];
		for(Case aCase :originalCases) {
		    Case aNewCase = emailToCases.get(aCase.SuppliedEmail);
		    if(aNewCase != null) {
                aNewCase.Don_t_Send_Auto_Response__c = true;
		    }
		}
    }
}