objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>MHF</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
                <value>
                    <fullName>Saks</fullName>
                </value>
                <value>
                    <fullName>Off 5th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>Replaces the standard Type field (relabeled Type Old)</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>BTO - Big Ticket Order (New Purchases)</fullName>
                </value>
                <value>
                    <fullName>Credit Hold</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivery (WISMO)</fullName>
                </value>
                <value>
                    <fullName>Delivery Resolution</fullName>
                </value>
                <value>
                    <fullName>Exchange / Return / Allowance (ERA)</fullName>
                </value>
                <value>
                    <fullName>Gift Card(s)</fullName>
                </value>
                <value>
                    <fullName>Gift Registry</fullName>
                </value>
                <value>
                    <fullName>Major Home Fashion</fullName>
                </value>
                <value>
                    <fullName>Order Inquiry</fullName>
                </value>
                <value>
                    <fullName>Order placed</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Place an order</fullName>
                </value>
                <value>
                    <fullName>Product Information</fullName>
                </value>
                <value>
                    <fullName>Refunds/Credits</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
                <value>
                    <fullName>Rewards</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
                <value>
                    <fullName>Store Experience</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Warranty</fullName>
                </value>
                <value>
                    <fullName>Executive Escalation Only</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Order System Error</fullName>
                </value>
                <value>
                    <fullName>Rewards Escalation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Case_Type_Validation__mdt.object
<CustomObject>
    <description>List of Case Types that require an order number on case create (used on contact form in the community)</description>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>Values from the Case.Case_Type__c field</description>
        <label>Case Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>BTO - Big Ticket Order (New Purchases)</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivery (WISMO)</fullName>
                </value>
                <value>
                    <fullName>Delivery Resolution</fullName>
                </value>
                <value>
                    <fullName>Exchange / Return / Allowance (ERA)</fullName>
                </value>
                <value>
                    <fullName>Gift Card(s)</fullName>
                </value>
                <value>
                    <fullName>Gift Registry</fullName>
                </value>
                <value>
                    <fullName>In Store Experience</fullName>
                </value>
                <value>
                    <fullName>Major Home Fashion</fullName>
                </value>
                <value>
                    <fullName>Order Inquiry</fullName>
                </value>
                <value>
                    <fullName>Order placed</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Place an order</fullName>
                </value>
                <value>
                    <fullName>Product Information</fullName>
                </value>
                <value>
                    <fullName>Refunds/Credits</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
                <value>
                    <fullName>Rewards</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Warranty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Type Validation</label>
    <pluralLabel>Case Type Validations</pluralLabel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_ContactSupportFormController.cls
/**
 * @Name trac_ContactSupportFormController
 * @Author Daniel Labonte, Traction on Demand
 * @Date June 13, 2019
 *
 * @Description apex controller for the contact support form lightning component
 */
public with sharing class trac_ContactSupportFormController {

    /**
     * @description retrieve the user id of the guest user
     * @return string of the user id
     */
    @AuraEnabled
    public static String getGuestUserId() {
        return [SELECT Id FROM User WHERE Name = 'Hudson Bay Site Guest User' OR UserType = 'guest' LIMIT 1].Id;
    }



    @AuraEnabled
    public static Map<String,String> getCaseFieldLabels(List<String> fields) {
        Map<String,String> fieldMap = new Map<String, String>();
        Map<String,SObjectField> sobjectFields = Schema.SObjectType.Case.fields.getMap();
        for(String field : fields) {
            fieldMap.put(field,sobjectFields.get(field).getDescribe().getLabel());
        }
        return fieldMap;
    }



    /**
     * @description retrieve picklist values for the case type field
     * @return map of the picklist values
     */
    @AuraEnabled
    public static List<Map<String,String>> getCaseTypeValues(String businessUnitValue) {
        List<String> values = TLPicklist.getDependantPicklistValuesByFieldName(
                'Case',
                'Business_Unit__c',
                'Type').get(businessUnitValue);
System.debug(values);
        List<Map<String,String>> picklistValues = new List<Map<String,String>>();
        for(String value : values) {
            picklistValues.add(new Map<String, String>{'label' => value, 'value' => value});
        }
        return picklistValues;
    }


    /**
     * @description retreive the case type picklist values from the org (custom metadata type)
     *              that required an order number on case create
     * @return list of picklist string values
     */
    @AuraEnabled
    public static List<String> getCaseTypeValidations() {
        List<String> caseTypeValues = new List<String>();
        for(Case_Type_Validation__mdt mdt : [SELECT Case_Type__c FROM Case_Type_Validation__mdt]) {
            caseTypeValues.add(mdt.Case_Type__c);
        }
        return caseTypeValues;
    }


    /**
     * @description create a new link between the uploaded files and the case created
     * @param caseId - newly created case
     * @param uploadedFileIds - list of json objects where { name : documentId }
     * @return whether the link was successfully created
     */
    @AuraEnabled
    public static String attachFilesToCase(String caseId, List<Map<String,String>> uploadedFileIds) {
        List<ContentDocumentLink> newDocumentLinks = new List<ContentDocumentLink>();
        List<String> ids = new List<String>();

        for(Map<String,String> file : uploadedFileIds) {
            ids.add(file.get('name')); // This is a JSON object where {name : documentId}
        }

        List<ContentDocumentLink> queriedDocumentLinks = [
                SELECT ContentDocumentId,Id,IsDeleted,LinkedEntityId,ShareType,SystemModstamp,Visibility
                FROM ContentDocumentLink
                WHERE ContentDocumentId IN :ids];

        for(ContentDocumentLink file : queriedDocumentLinks) {
            ContentDocumentLink newLink = file.clone(false);
            newLink.LinkedEntityId = caseId;
            newLink.ShareType = 'V'; // V C I
            newDocumentLinks.add(newLink);
        }

        String error = 'false';
        try {
            insert newDocumentLinks;
        } catch (Exception e) {
            error = e.getMessage();
        }

        try {
            if (error == 'false') delete queriedDocumentLinks;
        } catch (Exception e) {}

        return error;
    }
}