objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>MHF</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
                <value>
                    <fullName>Saks</fullName>
                </value>
                <value>
                    <fullName>Off 5th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Steward__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Steward</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>Replaces the standard Type field (relabeled Type Old)</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>BTO - Big Ticket Order (New Purchases)</fullName>
                </value>
                <value>
                    <fullName>Credit Hold</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivery (WISMO)</fullName>
                </value>
                <value>
                    <fullName>Delivery Resolution</fullName>
                </value>
                <value>
                    <fullName>Exchange / Return / Allowance (ERA)</fullName>
                </value>
                <value>
                    <fullName>Gift Card(s)</fullName>
                </value>
                <value>
                    <fullName>Gift Registry</fullName>
                </value>
                <value>
                    <fullName>Major Home Fashion</fullName>
                </value>
                <value>
                    <fullName>Order Inquiry</fullName>
                </value>
                <value>
                    <fullName>Order placed</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Place an order</fullName>
                </value>
                <value>
                    <fullName>Product Information</fullName>
                </value>
                <value>
                    <fullName>Refunds/Credits</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
                <value>
                    <fullName>Rewards</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
                <value>
                    <fullName>Store Experience</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Warranty</fullName>
                </value>
                <value>
                    <fullName>Executive Escalation Only</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Order System Error</fullName>
                </value>
                <value>
                    <fullName>Rewards Escalation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>4 MAN DELIVERY JOB</fullName>
                </value>
                <value>
                    <fullName>Account information update or question</fullName>
                </value>
                <value>
                    <fullName>Add Item to List</fullName>
                </value>
                <value>
                    <fullName>Add promotion code after purchase</fullName>
                </value>
                <value>
                    <fullName>Address Change Required</fullName>
                </value>
                <value>
                    <fullName>Allowance Request</fullName>
                </value>
                <value>
                    <fullName>Appliance Claim</fullName>
                </value>
                <value>
                    <fullName>Archived Accounts</fullName>
                </value>
                <value>
                    <fullName>Associate Loyalty Issue</fullName>
                </value>
                <value>
                    <fullName>Back Ordered Report</fullName>
                </value>
                <value>
                    <fullName>Better Business Bureau</fullName>
                </value>
                <value>
                    <fullName>Borderfree</fullName>
                </value>
                <value>
                    <fullName>Broken/Damaged Item</fullName>
                </value>
                <value>
                    <fullName>BTO</fullName>
                </value>
                <value>
                    <fullName>CA - Cancellation</fullName>
                </value>
                <value>
                    <fullName>Call Tag</fullName>
                </value>
                <value>
                    <fullName>Can I cancel my order?</fullName>
                </value>
                <value>
                    <fullName>Can I change my order?</fullName>
                </value>
                <value>
                    <fullName>Can you reactivate my gift card?</fullName>
                </value>
                <value>
                    <fullName>CASL Issue</fullName>
                </value>
                <value>
                    <fullName>Casper Mattress</fullName>
                </value>
                <value>
                    <fullName>Clear D</fullName>
                </value>
                <value>
                    <fullName>Credit Hold</fullName>
                </value>
                <value>
                    <fullName>Credit Points Dispute</fullName>
                </value>
                <value>
                    <fullName>CS - Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer asked for Store Information (phone number / details)</fullName>
                </value>
                <value>
                    <fullName>Customer Care Followup Alert</fullName>
                </value>
                <value>
                    <fullName>Customer Care Follow-Up Alerts (CCFU)</fullName>
                </value>
                <value>
                    <fullName>Customer preferred placing order over phone</fullName>
                </value>
                <value>
                    <fullName>Customer Reschedule Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Keep_Ownership__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Keep Ownership</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Address Issue</fullName>
                </value>
                <value>
                    <fullName>Alterations / repairs</fullName>
                </value>
                <value>
                    <fullName>Availability / assortment of merchandise</fullName>
                </value>
                <value>
                    <fullName>Bay PLCC/Mastercard Holder</fullName>
                </value>
                <value>
                    <fullName>BTO order not placed as customer paying with Gift Card</fullName>
                </value>
                <value>
                    <fullName>BTO order not placed as sale ended</fullName>
                </value>
                <value>
                    <fullName>BTO order not placed because of delivery date</fullName>
                </value>
                <value>
                    <fullName>BTO order not placed because of the DC pick up location</fullName>
                </value>
                <value>
                    <fullName>BTO order not placed because SKU is discontinued</fullName>
                </value>
                <value>
                    <fullName>BTO order not placed due to competitor pricing</fullName>
                </value>
                <value>
                    <fullName>BTO order not placed due to Out of Zone delivery cost</fullName>
                </value>
                <value>
                    <fullName>Call to MHF in error</fullName>
                </value>
                <value>
                    <fullName>Cancel at Door</fullName>
                </value>
                <value>
                    <fullName>Casper</fullName>
                </value>
                <value>
                    <fullName>Change a Reward Account Address</fullName>
                </value>
                <value>
                    <fullName>Change Rejected MOP</fullName>
                </value>
                <value>
                    <fullName>Credit Points Dispute</fullName>
                </value>
                <value>
                    <fullName>Cust /SA request for Special Delivery Arrangements</fullName>
                </value>
                <value>
                    <fullName>Cust call for Warranty/ Parts or In Home Repair</fullName>
                </value>
                <value>
                    <fullName>Customer f/up missed/cust. Waiting on update</fullName>
                </value>
                <value>
                    <fullName>Customer request for Compensation</fullName>
                </value>
                <value>
                    <fullName>Customer requests Return / Exchange out of policy</fullName>
                </value>
                <value>
                    <fullName>Custom wants to place an order</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DC Pick-Up Loc</fullName>
                </value>
                <value>
                    <fullName>Delay in issuing refund credit</fullName>
                </value>
                <value>
                    <fullName>Delivery fees</fullName>
                </value>
                <value>
                    <fullName>DP/Courier Issues (late delivery; damaged; returned to store; wrong address; left in rain)</fullName>
                </value>
                <value>
                    <fullName>DP - Driver concerns/service concerns</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Closed_Case_Email_Handler_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Closed Case Email Handler Settings</description>
    <fields>
        <fullName>Fields_To_Clone__c</fullName>
        <defaultValue>&apos;Description, AccountId, ContactId, AssetId, Origin, ContactEmail, Subject, Type, Category__c, Subcategory__c&apos;</defaultValue>
        <description>Comma separated list of fields to clone from the closed Case to the new Case</description>
        <inlineHelpText>Comma separated list of fields to clone from the closed Case to the new Case</inlineHelpText>
        <label>Fields To Clone</label>
        <type>TextArea</type>
    </fields>
    <label>Closed Case Email Handler Settings</label>
</CustomObject>

classes/trac_EmailMessageTriggerHelperTest.cls
/**
* @description Test Class for trac_EmailMessageTriggerHelper
* @author      Piyush Bansal, Traction on Demand
* @date        2019-12-12
*/
@isTest
public with sharing class trac_EmailMessageTriggerHelperTest {
    
    final static TLTestFactory factory = new TLTestFactory();
    @TestSetup
    static void testSetup(){ 
        List<Case> newCasesList=new List<Case>();
        Closed_Case_Email_Handler_Settings__c closedCaseEmailHandlerSettings = new Closed_Case_Email_Handler_Settings__c(
            Hours_Since_Closed_External__c = -10,
            Fields_to_clone__c = 'Description, AccountId, ContactId, ContactEmail, Subject, Case_Type__c, Category__c, Subcategory__c, RecordTypeId, OwnerId, Business_Unit__c'
        );
        insert closedCaseEmailHandlerSettings;
        Case tempCase = (Case)factory.createSObject(new Case(
            Subject = 'Subject Test',
            Description = 'testing',
            SuppliedEmail='test@abc.org',
            Status ='New',
            Priority = 'Medium',
            Business_Unit__c = 'MHF',
            RecordTypeId =TLSObj.getRecordTypeIdForName(Case.SObjectType, trac_CaseConstants.RECORD_TYPE_DEVNAME_SAKS),
            Origin = 'Web'), false);
        
        newCasesList = (List<Case>)factory.createSObjects(tempCase, 4, true);
       /* for(Case parentCase : newCasesList){
            parentCase.Case_Steward__c=parentCase.OwnerId;
            parentCase.Keep_Ownership__c=true;
            // parentCase.Status='Closed';
        }
        update newCasesList;*/
    }
    @istest
    static void insertEmailMessageTest(){
        List<Case> newCasesList = [SELECT Id,Status,OwnerId,Keep_Ownership__c,Business_Unit__c,SuppliedEmail,Subject,Description,Case_Steward__c FROM Case];
        List<EmailMessage> newEmailList=new List<EmailMessage>();
        for(Case parentCase:newCasesList){
            EmailMessage email = (EmailMessage)factory.createSObject(new EmailMessage(Incoming = true), false);
            email.FromAddress = parentCase.SuppliedEmail;
            email.ToAddress= parentCase.Id+'test@xyz.org';
            email.Subject = parentCase.Subject;
            email.HtmlBody = parentCase.Description;
            email.ParentId = parentCase.Id;
            newEmailList.add(email);
        }
        
        Test.startTest();
        insert newEmailList;
        Test.stopTest();
        System.assertEquals(8, [SELECT Id FROM EmailMessage].size());
    }
    
    /**
* Test that when a email message is sent to a closed case
* a new case is a created and email message is re-parented
*/
    @IsTest static void test_closed_case() {
        List<Case> newCasesList = [SELECT Id,Status,Business_Unit__c,SuppliedEmail,Subject,Description FROM Case];
        for(case cse : newCasesList){
            cse.status='Closed';
        }
        update newCasesList;
        EmailMessage testMsg = (EmailMessage)factory.createSObject(new EmailMessage(Incoming = true, ParentId=newCasesList[0].Id), false);
        testMsg.FromAddress = 'test@test.com';
        testMsg.toAddress = 'test@test.com';
        Test.startTest();
        insert testMsg;
        Test.stopTest();
        
        List<Case> resultCase = [SELECT Id,IsClosed FROM Case];
        List<EmailMessage> resultMsg= [SELECT Id, ParentId FROM EmailMessage WHERE Id =:testMsg.Id];
        
        System.assertEquals(newCasesList.size()+1, resultCase.size(), 'A new case should be created.');
        System.assertNotEquals(newCasesList[0].Id, resultMsg[0].ParentId, 'The Email message should be re-parented to the new case');
    }
    
    /**
*  @description Uses custom setting to specify a time that a case needs to be closed for before making a new one
*  @author      Jeremy Horan, Traction on Demand.
*  @date        4/30/2018
*/
    @IsTest static void test_closedCaseWithSetting() {  
        List<Case> newCasesList = [SELECT Id,Status,Business_Unit__c,SuppliedEmail,Subject,Description FROM Case];
        for(case cse : newCasesList){
            cse.status='Closed';
        }
        update newCasesList;
        EmailMessage testMsg = (EmailMessage)factory.createSObject(new EmailMessage(Incoming = true, HtmlBody = 'Test', ParentId = newCasesList[0].Id), false);
        testMsg.FromAddress = 'test@test.com';
        testMsg.toAddress = 'test@test.com';
        Test.startTest();
        insert testMsg;
        Test.stopTest();
        
        List<Case> resultCase = [SELECT Id,IsClosed FROM Case];
        List<EmailMessage> resultMsg= [SELECT Id, ParentId FROM EmailMessage WHERE Id =:testMsg.Id];
        
        System.assertEquals(newCasesList.size()+1, resultCase.size(), 'A new case should be created.');
        System.assertNotEquals(newCasesList[0].Id, resultMsg[0].ParentId, 'The Email message should be re-parented to the new case');
    }
    
    /**
*  @description Uses custom setting to specify a time that a case needs to be closed for before making a new one
*               Shouldn't reparent if the case hasn't been closed long enough
*  @author      Jeremy Horan, Traction on Demand.
*  @date        4/30/2018
*/
    @IsTest static void test_closedCaseWithSettingNoReparent() {
        
        List<Case> newCasesList = [SELECT Id,Status,Business_Unit__c,SuppliedEmail,Subject,Description FROM Case];
        for(case cse : newCasesList){
            cse.status='Closed';
        }
        update newCasesList;
        EmailMessage testMsg = (EmailMessage)factory.createSObject(new EmailMessage(Incoming = true, ParentId = newCasesList[0].Id), false);
        testMsg.FromAddress = 'test@test.com';
        testMsg.toAddress = 'test@test.com';
        Test.startTest();
        insert testMsg;
        Test.stopTest();
        
        List<Case> resultCase = [SELECT Id FROM Case];
        List<EmailMessage> resultMsg= [SELECT Id, ParentId FROM EmailMessage WHERE Id =:testMsg.Id];
        
        System.assertEquals(newCasesList.size()+1, resultCase.size());
    }
    
    /**
* Test that when a email message is sent to a new case
* no new case is created
*/
    @IsTest static void test_new_case() {
        
        List<Case> newCasesList = [SELECT Id,Status,Business_Unit__c,SuppliedEmail,Subject,Description FROM Case];
        EmailMessage testMsg = (EmailMessage)factory.createSObject(new EmailMessage(Incoming = true, ParentId = newCasesList[0].Id), false);
        testMsg.FromAddress = 'test@test.com';
        testMsg.HtmlBody='test';
        testMsg.toAddress = 'test@test.com';
        Test.startTest();
        insert testMsg;
        Test.stopTest();
        
        List<Case> resultCase = [SELECT Id FROM Case WHERE Status= 'New'];
        List<EmailMessage> resultMsg= [SELECT Id, ParentId FROM EmailMessage WHERE Id =:testMsg.Id];
        
        System.assertEquals(newCasesList.size(), resultCase.size(), 'A new case should not be created.');
    }
}