objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auto_Email_Status__c</fullName>
        <description>Populated via a batch job. Used in the process managing awaiting internal and customer response process.</description>
        <label>Auto Email Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Day 5</fullName>
                </value>
                <value>
                    <fullName>Customer Day 7</fullName>
                </value>
                <value>
                    <fullName>Internal Day 1</fullName>
                </value>
                <value>
                    <fullName>Internal Day 2</fullName>
                </value>
                <value>
                    <fullName>Not Set</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Status_Change__c</fullName>
        <description>Stores the last time the status changed -- used by the Case Business Hours Tools package.</description>
        <label>Last Status Change</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/trac_EmailStatusBatchTest.cls
/**
 *  @description Tests for trac_EmailStatusBatch
 *  @author      Jeremy Horan, Traction on Demand.
 *  @date        9/12/2019
 */
@IsTest
private class trac_EmailStatusBatchTest {

    static final TLTestFactory factory = new TLTestFactory();

    @IsTest
    static void testBatch() {
        Case testCase = (Case) factory.createSObject(new Case(Status = trac_CaseConstants.STATUS_AWAITING_CUSTOMER), true);

        testCase.Last_Status_Change__c = Datetime.now().addDays(-6);
        update testCase;


        Test.startTest();
        Database.executeBatch(new trac_EmailStatusBatch(), 50);
        Test.stopTest();

        Case queriedCase = [SELECT Id, Auto_Email_Status__c FROM Case WHERE Id = :testCase.Id];

        System.assertEquals(trac_CaseConstants.EMAIL_STATUS_CUSTOMER_5, queriedCase.Auto_Email_Status__c, 'Case Email Status should be set based on last status update');
    }

    @IsTest
    static void testScheduler() {
        String CRON_EXP = '0 0 0 19 6 ? 2099';

        Test.startTest();
        trac_EmailStatusBatch emailStatusBatch = new trac_EmailStatusBatch();
        String jobId = System.schedule('TestEmailStatusBatch', CRON_EXP, emailStatusBatch);
        Test.stopTest();

        System.assert(jobId != null);
    }
}