objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>MHF</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
                <value>
                    <fullName>Saks</fullName>
                </value>
                <value>
                    <fullName>Off 5th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UCID_Number__c</fullName>
        <description>External ID from UCID (Contact MDM)</description>
        <externalId>true</externalId>
        <label>UCID Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_External_Id__c</fullName>
        <description>Business Unit concatenated with UCID number for a unique external ID</description>
        <externalId>true</externalId>
        <inlineHelpText>Business Unit concatenated with UCID number for a unique external ID</inlineHelpText>
        <label>Unique External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Web_Service_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Settings for Web Services
- Default Endpoints &amp; Other Parameters</description>
    <fields>
        <fullName>API_Key__c</fullName>
        <description>HBC Gateway API Key</description>
        <label>API Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Base_Url__c</fullName>
        <label>Base Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Order_Endpoint__c</fullName>
        <description>OMS Create Order relative Endpoint</description>
        <label>Create Order Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Get_Order_Details_Endpoint__c</fullName>
        <description>OMS Get Order Details relative Endpoint</description>
        <label>Get Order Details Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Get_Order_List_Endpoint__c</fullName>
        <description>OMS Get Order List Service relative Endpoint</description>
        <label>Get Order List Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UCID_Create_Endpoint__c</fullName>
        <description>UCID Create Service relative Endpoint</description>
        <label>UCID Create Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UCID_Query_Endpoint__c</fullName>
        <description>UCID Query Service relative endpoint</description>
        <label>UCID Query Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UCID_Update_Endpoint__c</fullName>
        <description>UCID Update Service relative endpoint</description>
        <label>UCID Update Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Update_Order_Endpoint__c</fullName>
        <description>OMS Update Order relative Endpoint</description>
        <label>Update Order Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Web Service Settings</label>
</CustomObject>

classes/trac_ContactSearchControllerTest.cls
/**
 * @description Test class for trac_ContactSearchController
 * @author      Rajat Agrawal, Traction on Demand
 * @date        2019-07-08
 */
@IsTest
private class trac_ContactSearchControllerTest {

    static final TLTestFactory factory = new TLTestFactory();

    @IsTest
    static void testGetContacts() {
        /*Web_Service_Settings__c settings = new Web_Service_Settings__c(
                API_Key__c = 'BAgIdATJjI1jJ5ytc0Onq7JQYOrGNfsNPPoKxUN5',
                Create_Order_Endpoint__c = '/orders',
                Get_Order_Details_Endpoint__c = '/orders/details',
                UCID_Create_Endpoint__c = '/customers/me',
                Timeout__c = 120000,
                Base_Url__c = 'https://uat.thebay.com/live',
                Update_Order_Endpoint__c = '/orders',
                Get_Order_List_Endpoint__c = '/orders/list',
                UCID_Update_Endpoint__c = '/customers/me',
                UCID_Query_Endpoint__c = '/customers/search'
        );
        insert settings;*/
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        List<Contact> contacts = new List<Contact>();
        Contact con = new Contact(LastName = 'Test');
        contacts = trac_ContactSearchController.getContacts(con);
        System.assert(contacts.size() > 0, 'Contacts not found.');
    }

    @IsTest
    static void testUpsertContact() {
        Contact con = (Contact)factory.createSObject(new Contact(UCID_Number__c = 'UCID123455', Business_Unit__c = 'MHF'), false);
        Test.startTest();
        Contact updatedCon = trac_ContactSearchController.upsertContact(con);
        Test.stopTest();
        System.assertEquals(con.Business_Unit__c + '-' + con.UCID_Number__c, updatedCon.Unique_External_Id__c, 'Contact not updated.');
    }

    @IsTest
    static void testUpdateCase() {
        Contact con = (Contact)factory.createSObject(new Contact(Business_Unit__c = 'MHF'), true);
        Case cs = (Case)factory.createSObject(new Case(), true);
        Test.startTest();
        Id caseId = trac_ContactSearchController.updateCase(con, cs.Id);
        Test.stopTest();
        Case updatedCase = [SELECT Id, Business_Unit__c FROM Case WHERE Id =: caseId];
        System.assertEquals(con.Business_Unit__c, updatedCase.Business_Unit__c, 'Case not updated.');
    }
}