objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Loyalty_Id__c</fullName>
        <label>Customer Loyalty Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Integration_Error__c.object
<CustomObject>
    <description>Stores integration errors.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The URL of the endpoint where the payload was sent</description>
        <inlineHelpText>The URL of the endpoint where the payload was sent</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_CaseLoyaltyController.cls
public with sharing class trac_CaseLoyaltyController {
    @AuraEnabled(Cacheable=true)
    public static TLAuraResponse getConversionRate() {
        TLAuraResponse response = new TLAuraResponse(true);
        trac_WS_LoyaltyPointValue request = new trac_WS_LoyaltyPointValue();

        try {
            if(request.send()) {
                response.returnValuesMap.put('body', request.pointValueResponse);
            } else {
                response = new TLAuraResponse(false, 'communication error with merkle');
                response.returnValuesMap.put('body', request.getBody());
            }
            response.returnValuesMap.put('statusCode', request.getStatusCode());
        } catch (Exception e) {
            System.debug(e.getMessage());
            Integration_Error__c integrationError = trac_IntegrationError.addError(new Integration_Error__c(
                    Description__c = e.getMessage() + '\n' + e.getStackTraceString(),
                    Endpoint__c = request.ENDPOINT,
                    Service__c = 'Loyalty Lookup'
            ));
            insert integrationError;

            String errorMessage = trac_WS_WebServiceHelper.DEFAULT_ERROR + integrationError.Id;

            throw new CaseLoyaltyException(errorMessage);
        }

        return response;
    }

    @AuraEnabled
    public static void unsetCustomerLoyaltyId(Id caseId) {
        Case cs = new Case(Id = caseId, Customer_Loyalty_Id__c = null);
        update cs;
    }

    public class CaseLoyaltyException extends Exception {}

}