objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Power of one field for reports</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Order_Refund_Credit__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Charged__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Line item or full order amount depending on ORC Type (excludes tax and shipping fee) - Discounted Amount (ie actual amount charged)</description>
        <inlineHelpText>Line item or full order amount depending on ORC Type</inlineHelpText>
        <label>Amount Charged ORC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_to_Refund__c</fullName>
        <formula>if(OR(ispickval( Reason__c , &quot;Order Not Received&quot;)=TRUE, Quantity__c = Quantity_Not_Received__c ), Amount_Charged__c,Amount_Charged__c - Adjusted_Price__c) + if( Credit_Shipping_Fee__c =TRUE, Shipping_Fee__c ,0)+Other_Refund__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ORC Amount to Refund</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case associated to the ORC</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Refunds/Credits</relationshipLabel>
        <relationshipName>Order_Refunds_Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ORC_Status__c</fullName>
        <label>ORC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Requires Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Number__c</fullName>
        <label>Transaction Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Order Refund/Credit</label>
    <nameField>
        <displayFormat>ORC-{0000000}</displayFormat>
        <label>Order Refund/Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Refunds/Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/trac_OrderRefundCreditHelperTest.cls
/**
 *  @description Tests for trac_OrderRefundCreditHelper
 *  @author      Jeremy Horan, Traction on Demand.
 *  @date        8/9/2019
 */
@IsTest
private class trac_OrderRefundCreditHelperTest {

    static final TLTestFactory factory = new TLTestFactory();

    @IsTest
    static void test_setCaseStatus() {
        Case parentCase = (Case) factory.createSObject(new Case(Status = trac_CaseConstants.STATUS_NEW), true);

        Order_Refund_Credit__c orderRefundCredit = (Order_Refund_Credit__c) factory.createSObject(new Order_Refund_Credit__c(Case__c = parentCase.Id), true);

        orderRefundCredit.ORC_Status__c = trac_OrderRefundCreditConstants.STATUS_APPROVED;
        update orderRefundCredit;

        Case queriedCase = [SELECT Id, Status FROM Case WHERE Id = :parentCase.Id];

        System.assertNotEquals(trac_CaseConstants.STATUS_NEW, queriedCase.Status, 'Status should\'ve been updated by ORC approval');
    }

    @IsTest
    static void test_postOnParentCase() {
        Case parentCase = (Case) factory.createSObject(new Case(Status = trac_CaseConstants.STATUS_NEW), true);

        Order_Refund_Credit__c orderRefundCredit = (Order_Refund_Credit__c) factory.createSObject(new Order_Refund_Credit__c(Case__c = parentCase.Id, Transaction_Number__c='123456789', Amount_Charged__c=50), true);

        Test.startTest();
        orderRefundCredit.ORC_Status__c = trac_OrderRefundCreditConstants.STATUS_CLOSED;
        update orderRefundCredit;
        Test.stopTest();

        List<Order_Refund_Credit__c> orcList = new List<Order_Refund_Credit__c>([SELECT Id,Name, Transaction_Number__c,Amount_to_Refund__c FROM Order_Refund_Credit__c WHERE Id=: orderRefundCredit.Id]);
        List<FeedItem> feedList = new List<FeedItem>([SELECT Id, ParentId, Body FROM FeedItem WHERE ParentId =:parentCase.Id]);

        System.assertEquals(True, feedList[0].Body.contains(orcList[0].Name+' - '+orcList[0].Transaction_Number__c+' - '+orcList[0].Amount_to_Refund__c), 'Feed successfully posted on Parent Case');
    }
}