objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Owner_Location__c</fullName>
        <formula>TEXT(Owner:User.Agent_Location__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Owner Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Owner_Supervisor_ID__c</fullName>
        <formula>Owner:User.ManagerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Owner Supervisor ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Power of one field for reports</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Case_Time_Log__c.object
<CustomObject>
    <description>Time Log records for the Case object. A snapshot of Case fields and time calculations when closed.</description>
    <fields>
        <fullName>Agent_Location__c</fullName>
        <description>The location of the agent working on the case</description>
        <inlineHelpText>The location of the agent working on the case</inlineHelpText>
        <label>Agent Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Jackson</fullName>
                </value>
                <value>
                    <fullName>Cebu</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Moncton</fullName>
                </value>
                <value>
                    <fullName>Manilla</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Agent_Team_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The agent on the time logs team lead</description>
        <inlineHelpText>The agents team lead</inlineHelpText>
        <label>Agent Team Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Time_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent object lookup</description>
        <inlineHelpText>This is the link up to the Case record (parent record) for this Time Log record.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Time Logs</relationshipLabel>
        <relationshipName>Case_Time_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Time Log</label>
    <nameField>
        <displayFormat>CTL-{00000}</displayFormat>
        <label>Time Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Time Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_CaseTimeLogTriggerHelperTest.cls
/**
* @description Test class for trac_CaseTimeLogTrigger
* @author      Abhishek Solanki, Traction on Demand
* @date        2019-12-13
*/
@IsTest
public class trac_CaseTimeLogTriggerHelperTest {
    static final TLTestFactory factory = new TLTestFactory();
    
    @TestSetup
    static void setupTestData(){
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'][0];

        User supervisor = (User) factory.createSObject(new User(
            Username = TLString.generateRandomString(10) + '@supervisor.com',
            Email = 'test@username.com',
            ProfileId = adminProfile.Id,
            Lastname = 'Test',
            Alias = 'test123',
            TimeZoneSidKey = 'America/Chicago',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US'
        ), true);
        User caseOwner = (User) factory.createSObject(new User(
                Username = TLString.generateRandomString(10) + '@username.com',
                Email = 'owner@username.com',
                ProfileId = adminProfile.Id,
                Lastname = 'owner',
                Alias = 'owner123',
                ManagerId=supervisor.Id,
                Agent_Location__c = 'Cebu',
                TimeZoneSidKey = 'America/Chicago',
                LanguageLocaleKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LocaleSidKey = 'en_US'
        ), true);
        factory.createSObject(new Case(
            Subject='Test Subject',
            Origin='Phone',
            Status='New',
            OwnerId=caseOwner.Id
        ), true);
    }
    
    @IsTest
    static void test_updateTeamLeadAndLocation() {
        Case_Time_Log__c newCaseTimeLog = (Case_Time_Log__c) factory.createSObject(new Case_Time_Log__c(),false);
        List<Case> caseList = new List<Case>([SELECT Id,Case_Owner_Supervisor_ID__c,Case_Owner_Location__c FROM Case WHERE Subject = 'Test Subject']);
        if(caseList!=null && !caseList.isEmpty()){
            newCaseTimeLog.Case__c = caseList[0].Id;
        }
        Test.startTest();
        Insert newCaseTimeLog;
        Test.stopTest();
        List<Case_Time_Log__c> ctlList = new List<Case_Time_Log__c>([SELECT Agent_Team_Lead__c,Agent_Location__c FROM Case_Time_Log__c WHERE Id =: newCaseTimeLog.Id]);
        System.assertEquals(caseList[0].Case_Owner_Supervisor_ID__c, ctlList[0].Agent_Team_Lead__c, 'Case Owner Supervisor succesfully mapped to Agent Team Lead of Case Time Log');
        System.assertEquals(caseList[0].Case_Owner_Location__c,  ctlList[0].Agent_Location__c, 'Case Owner Location succesfully mapped to Agent Location of Case Time Log');
    }
}