objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Power of one field for reports</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Order_Refund_Credit__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case associated to the ORC</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Refunds/Credits</relationshipLabel>
        <relationshipName>Order_Refunds_Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ORC_Status__c</fullName>
        <label>ORC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Requires Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Refund/Credit</label>
    <nameField>
        <displayFormat>ORC-{0000000}</displayFormat>
        <label>Order Refund/Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Refunds/Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/trac_OrderRefundCreditCleanupBatch.cls
/**
 *  @description Batch to handle uncompleted ORCs on closed cases
 *  @author      Jeremy Horan, Traction on Demand.
 *  @date        9/10/2019
 */
global class trac_OrderRefundCreditCleanupBatch implements Database.Batchable<SObject>, Schedulable {

    global Database.QueryLocator start(Database.BatchableContext batchableContext) {
        return Database.getQueryLocator([SELECT Id, ORC_Status__c, Case__c FROM Order_Refund_Credit__c WHERE Case__r.IsClosed = true AND ORC_Status__c = :trac_OrderRefundCreditConstants.STATUS_DRAFT]);
    }

    global void execute(Database.BatchableContext batchableContext, List<Order_Refund_Credit__c> scope) {
        for (Order_Refund_Credit__c orderRefundCredit : scope) {
            orderRefundCredit.ORC_Status__c = trac_OrderRefundCreditConstants.STATUS_CANCELLED;
        }

        update scope;
    }

    global void finish(Database.BatchableContext batchableContext) {}

    //Schedule batch job
    global void execute(SchedulableContext schedulableContext) {
        Database.executeBatch(new trac_OrderRefundCreditCleanupBatch(), 200);
    }

}