objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <description>Power of one field for reports</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Promo_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Stamped when promo code is associated to the case. Added to the case close email</description>
        <label>Promo Code</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Promo_Code__c.object
<CustomObject>
    <fields>
        <fullName>Amount_List__c</fullName>
        <label>Amount</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$5.00</fullName>
                </value>
                <value>
                    <fullName>5%</fullName>
                </value>
                <value>
                    <fullName>$10.00</fullName>
                </value>
                <value>
                    <fullName>10%</fullName>
                </value>
                <value>
                    <fullName>$15.00</fullName>
                </value>
                <value>
                    <fullName>15%</fullName>
                </value>
                <value>
                    <fullName>$20.00</fullName>
                </value>
                <value>
                    <fullName>20%</fullName>
                </value>
                <value>
                    <fullName>$25.00</fullName>
                </value>
                <value>
                    <fullName>25%</fullName>
                </value>
                <value>
                    <fullName>$30.00</fullName>
                </value>
                <value>
                    <fullName>30%</fullName>
                </value>
                <value>
                    <fullName>$35.00</fullName>
                </value>
                <value>
                    <fullName>35%</fullName>
                </value>
                <value>
                    <fullName>$40.00</fullName>
                </value>
                <value>
                    <fullName>40%</fullName>
                </value>
                <value>
                    <fullName>45.00$</fullName>
                </value>
                <value>
                    <fullName>45%</fullName>
                </value>
                <value>
                    <fullName>$50.00</fullName>
                </value>
                <value>
                    <fullName>50%</fullName>
                </value>
                <value>
                    <fullName>$55.00</fullName>
                </value>
                <value>
                    <fullName>55%</fullName>
                </value>
                <value>
                    <fullName>$60.00</fullName>
                </value>
                <value>
                    <fullName>60%</fullName>
                </value>
                <value>
                    <fullName>$65.00</fullName>
                </value>
                <value>
                    <fullName>65%</fullName>
                </value>
                <value>
                    <fullName>$70.00</fullName>
                </value>
                <value>
                    <fullName>70%</fullName>
                </value>
                <value>
                    <fullName>$75.00</fullName>
                </value>
                <value>
                    <fullName>75%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Promo Codes</relationshipLabel>
        <relationshipName>Promo_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consumed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consumed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Promo_Codes_Consumed_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consumed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consumed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Promo_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Promo Code</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Promo Code</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promo Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_GetPromoCode.cls
/**
* @Name trac_GetPromoCode
* @Author Daniel Labonte, Traction on Demand
* @Date June 28, 2019 
* 
* @Description ${DESCRIPTION}
*/

public with sharing class trac_GetPromoCode {
    /**
* @description method to retrieve available promo code records
* @param value query based on promo code amount
* @return list of available promo code records
*/
    @AuraEnabled
    public static Object getPromoCode(String value) {
        String searchValue = '%' + value + '%';
        String query = 'SELECT Id, Amount_List__c, Name, Promo_Code__c FROM Promo_Code__c WHERE Case__c = null AND Consumed__c = FALSE AND Amount_List__c LIKE \'' + searchValue + '\' FOR UPDATE';
        return Database.query(query);
    }

    /**
* @description method to associate promo code records with a case record and stamp the user who performed the action
* @param promoCodeRecords map of promo code record ids
* @param caseId string of the case record id
* @return boolean of if there was an error
*/
    @AuraEnabled
    public static Boolean consumePromoCodes(Map<String, String> promoCodeRecords, String caseId) {
        Boolean success = true;

        try {
            List<String> ids = new List<String>();
            List<Promo_Code__c> promoCodesToUpdate = new List<Promo_Code__c>();
            for (String promoCodeId : promoCodeRecords.keySet()) {
                promoCodesToUpdate.add(new Promo_Code__c(
                        Id = promoCodeId,
                        Case__c = caseId,
                        Consumed_By__c = UserInfo.getUserId(),
                        Consumed__c = true
                ));
            }

            if (promoCodeRecords.keySet().size() == [SELECT Id FROM Promo_Code__c WHERE Id IN :promoCodeRecords.keySet() AND Consumed__c = FALSE].size()) {

                success = false;
                List<Database.SaveResult> srs = Database.update(promoCodesToUpdate);
                for (Database.SaveResult sr : srs) {
                    if (!sr.isSuccess()) {
                        success = true;
                    }
                }
            }
        } catch (Exception e) {
            throw new PromoCodeException(e.getMessage());
        }
        return success;
    }
    private class PromoCodeException extends Exception {
    }
}