objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Time_with_Agents__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Business Time with Agents</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Time_with_Company__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Business Time with Company</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Time_with_Customers__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Business Time with Customers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Time_with_Queues__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Business Time with Queues</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calendar_Time_with_Agents__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Calendar Time with Agents</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calendar_Time_with_Company__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Calendar Time with Company</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calendar_Time_with_Customers__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Calendar Time with Customers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calendar_Time_with_Queues__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Calendar Time with Queues</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Power of one field for reports</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Close_Date_Time__c</fullName>
        <label>First Close Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>First_Close_Duration_Business__c</fullName>
        <defaultValue>0</defaultValue>
        <label>First Close Duration Business</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Close_Duration_Calendar__c</fullName>
        <defaultValue>0</defaultValue>
        <label>First Close Duration Calendar</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Close_Owner__c</fullName>
        <description>The Case Owner for the first time the Case was set to a Closed type Status.</description>
        <inlineHelpText>The Case Owner for the first time the Case was set to a Closed type Status.</inlineHelpText>
        <label>First Close Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Agent_changes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. Agent changes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Owner_changes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. Owner changes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Queue_changes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. Queue changes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Status_changes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. Status changes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reopened_Flag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reopened Flag</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_BusinessTime__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total BusinessTime</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Calender_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Calendar Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Case_Time_Log__c.object
<CustomObject>
    <description>Time Log records for the Case object. A snapshot of Case fields and time calculations when closed.</description>
    <fields>
        <fullName>Business_Hours_Duration__c</fullName>
        <description>Calculate business time duration when a Time Log record &quot;closes&quot; in seconds.</description>
        <inlineHelpText>Number of seconds this Time Log record had during business hours.</inlineHelpText>
        <label>Business Hours Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calendar_Duration__c</fullName>
        <description>Calculate calendar time duration when a Time Log record &quot;closes&quot;</description>
        <inlineHelpText>Number of seconds this Time Log record had in calendar time. Calendar time includes both business hours time and non business hours time.</inlineHelpText>
        <label>Calendar Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Status_Change__c</fullName>
        <description>If  Case Status equals Case Status New set to 0, else set to 1.</description>
        <formula>IF( Case_Status__c = Case_Status_New__c, 0, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>1 in this field indicates that the Case Status has changed.</inlineHelpText>
        <label>Case Status Change</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Status_Group__c</fullName>
        <description>This field allows categorization of the Case Status values into Customer or Company for reporting purposes.  Edit the formula below as required to account for the values in the Case Status field.</description>
        <formula>/* EDIT THIS FORMULA AS REQUIRED TO MATCH THE CASE STATUS FIELD VALUES */
/* THIS IS AN EXAMPLE ONLY */
/*                         */
Case ( Case_Status__c , 
&quot;Team Assistance Needed&quot;,&quot;Company&quot;, 
&quot;Awaiting Service Excellence Review&quot;,&quot;Company&quot;, 
&quot;POS Team&quot;,&quot;Company&quot;, 
&quot;Pending Fraud Team&quot;,&quot;Company&quot;, 
&quot;System Issue&quot;,&quot;Company&quot;, 
&quot;Awaiting Customer Response&quot;,&quot;Customer&quot;, 
&quot;Awaiting Internal Response&quot;,&quot;Company&quot;, 
&quot;Response Received&quot;,&quot;Company&quot;, 
&quot;New&quot;,&quot;Company&quot;, 
&quot;In Progress&quot;,&quot;Company&quot;, 
&quot;Closed&quot;,&quot;Customer&quot;, 
&quot;Company&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field allows categorization of the Case Status values into Customer or Company for reporting purposes.</inlineHelpText>
        <label>Case Status Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Status_New__c</fullName>
        <description>The value of the Case Status field when the Time Log record was closed / ended.</description>
        <inlineHelpText>The value of the Case Status field when the Time Log record was closed / ended.</inlineHelpText>
        <label>Case Status New</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent object lookup</description>
        <inlineHelpText>This is the link up to the Case record (parent record) for this Time Log record.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Time Logs</relationshipLabel>
        <relationshipName>Case_Time_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_Type__c</fullName>
        <description>This field indicates whether the Parent record Owner was a User or a Queue.</description>
        <inlineHelpText>This field indicates whether the Parent record Owner was a User or a Queue.</inlineHelpText>
        <label>Owner Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Owner_Change__c</fullName>
        <description>Set value to 1 if Parent Owner is not the same as Parent Owner New</description>
        <formula>IF ( Parent_Owner__c =  Parent_Owner_New__c, 0, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Set value to 1 if Parent Owner is not the same as Parent Owner New.   This allows the counting of how many times Case Ownship changed.</inlineHelpText>
        <label>Parent Owner Change</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Owner_New__c</fullName>
        <description>This field contains the value of the Parent record Owner that caused this Time Log record to be &quot;closed&quot;. This is the text value of the Case Owner field (Parent record Owner). This field can be used for reporting as it includes both the User and Queue names in the same field. Changes to other fields being tracked will cause this field to be updated, but not changed when the Time Log record is created for other changes.</description>
        <inlineHelpText>This is the Owner of the Parent record at the time the time log record was closed.  This value is updated when the Parent record&apos;s Owner changes, otherwise it doesn&apos;t change, since the Owner hasn&apos;t actually changed on the Parent record.</inlineHelpText>
        <label>Parent Owner New</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Owner_User_New__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User object lookup, indicating the User that was the Owner of the Case record at the time the Time Log record was CLOSED; the new &quot;Owner&quot; when the owner of the parent record changes.</description>
        <inlineHelpText>User object lookup, indicating the User that was the Owner of the Case record at the time the Time Log record was CLOSED; the new &quot;Owner&quot; when the owner of the parent record changes.</inlineHelpText>
        <label>Case Owner New - User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Time_Logs_Owner_User_New</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Owner__c</fullName>
        <description>This is the text value of the Case Owner field (Parent record Owner). This field can be used for reporting as it includes both the User and Queue names in the same field.</description>
        <inlineHelpText>This is the text value of the Case Owner field (Parent record Owner). This field can be used for reporting as it includes both the User and Queue names in the same field.</inlineHelpText>
        <label>Parent Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Time Log</label>
    <nameField>
        <displayFormat>CTL-{00000}</displayFormat>
        <label>Time Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Time Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/todft_CaseService.cls
/**
 * Service class for Case object
 * @author Shubham Jain, Traction on Demand
 * @date 2019-08-01
 */
public without sharing class todft_CaseService {

    /**
	 * @description Check Case's closed status, also check if case is reopened.
	 * @param newRecords - sObject Records being processed
	 * @param oldRecordMap - old record's map
	 */
    public static void checkCaseStatus(List<sObject> newRecords, Map<Id, sObject> oldRecordMap) {
        List<Case> casesToUpdateTimeLogInfo = new List<Case>();
        List<Case> casesToUpdateReopenedInfo = new List<Case>();
        List<Case> newCases = new List<Case>();
        Map<Id, Case> oldCaseMap = new Map<Id, Case>();
        //Typecast sobject list into Case's list
        for (sObject sobj : newRecords) {
            newCases.add((Case) sobj);
        }

        //Typecast sObject map into Case's map
        for (Id sId : oldRecordMap.keySet()) {
            oldCaseMap.put(sId, (Case) oldRecordMap.get(sId));
        }

        for (Case cs : newCases) {
            //Check if case closed
            if ((cs.IsClosed || cs.IsClosedOnCreate) && !oldCaseMap.get(cs.Id).IsClosed) {
                casesToUpdateTimeLogInfo.add(cs);
            }
            //Check if case reopened.
            if ((!cs.IsClosed) && oldCaseMap.get(cs.Id).IsClosed) {
                casesToUpdateReopenedInfo.add(cs);
            }
        }

        if (!casesToUpdateTimeLogInfo.isEmpty())
            updateTimeLogInformationOnCase(casesToUpdateTimeLogInfo, oldCaseMap);

        if (!casesToUpdateReopenedInfo.isEmpty())
            updateCaseReopenedInfo(casesToUpdateReopenedInfo);
    }

    /**
	 * @description Updates Time Log fields on Case record.
	 * @param casesToProcess - case records being processed
	 * @param oldCaseMap - old case records map
	 */
    public static void updateTimeLogInformationOnCase(List<Case> casesToProcess, Map<Id, Case> oldCaseMap) {
        Set<Id> caseIds = new Map<Id, Case>(casesToProcess).keySet();
        Map<Id, List<Case_Time_Log__c>> caseTimeLogsByCaseIds = new Map<Id, List<Case_Time_Log__c>>();
        List<Case> caseListToUpdate = new List<Case>();
        Case cs;
        //Query time log records
        for (Case_Time_Log__c thisLog : [
                SELECT Id, Business_Hours_Duration__c, Calendar_Duration__c, Case__c
                        , Case_Status_Change__c, Owner_Type__c, Parent_Owner_Change__c
                        , Parent_Owner_New__c, Case_Status_Group__c, Parent_Owner_User_New__c
                        , Parent_Owner__c, Case_Status_New__c
                FROM Case_Time_Log__c
                WHERE Case__c IN :caseIds
        ]) {
            List<Case_Time_Log__c> caseTimeLogs = caseTimeLogsByCaseIds.get(thisLog.Case__c);
            if (caseTimeLogs == null)
                caseTimeLogs = new List<Case_Time_Log__c>();
            caseTimeLogs.add(thisLog);
            caseTimeLogsByCaseIds.put(thisLog.Case__c, caseTimeLogs);
        }

        //Get Case owner's name
        Map<Id, String> ownerNameByCaseIds = getCaseOwnerName(caseTimeLogsByCaseIds.keySet());

        //Loop over caseTimeLogsByCaseIds map
        for (Id caseId : caseTimeLogsByCaseIds.keySet()) {
            cs = createCaseInstance(caseId);
            for (Case_Time_Log__c thisLog : caseTimeLogsByCaseIds.get(caseId)) {
                //Check if it is a Owner Change log
                if (thisLog.Parent_Owner_Change__c == 1 && thisLog.Parent_Owner_New__c != null) {
                    cs.No_Owner_changes__c += 1;
                    if (thisLog.Parent_Owner_User_New__c == null) {
                        cs.No_Queue_changes__c += 1;
                    } else {
                        cs.No_Agent_changes__c += 1;
                    }
                }
                //Check if it is a status change log.
                if (thisLog.Case_Status_Change__c == 1) {
                    cs.No_Status_changes__c += 1;
                }
                //Check if Case Status Group is Company
                if (thisLog.Case_Status_Group__c == todft_TimeLogAggregationConstants.CASE_STATUS_GROUP_COMPANY) {
                    cs.Calendar_Time_with_Company__c
                            = thisLog.Calendar_Duration__c != null ?
                            cs.Calendar_Time_with_Company__c + thisLog.Calendar_Duration__c : cs.Calendar_Time_with_Company__c;

                    cs.Business_Time_with_Company__c
                            = thisLog.Business_Hours_Duration__c != null ?
                            cs.Business_Time_with_Company__c + thisLog.Business_Hours_Duration__c : 0;
                }
                //Check if Case Status Group is Customer
                if (thisLog.Case_Status_Group__c == todft_TimeLogAggregationConstants.CASE_STATUS_GROUP_CUSTOMER) {
                    cs.Business_Time_with_Customers__c
                            = thisLog.Business_Hours_Duration__c != null ?
                            cs.Business_Time_with_Customers__c + thisLog.Business_Hours_Duration__c : cs.Business_Time_with_Customers__c;

                    cs.Calendar_Time_with_Customers__c
                            = thisLog.Calendar_Duration__c != null ?
                            cs.Calendar_Time_with_Customers__c + thisLog.Calendar_Duration__c : cs.Calendar_Time_with_Customers__c;
                }

                //Check if owner type is User
                if (thisLog.Owner_Type__c == todft_TimeLogAggregationConstants.OWNER_TYPE_USER) {
                    cs.Business_Time_with_Agents__c
                            = thisLog.Business_Hours_Duration__c != null ?
                            cs.Business_Time_with_Agents__c + thisLog.Business_Hours_Duration__c : cs.Business_Time_with_Agents__c;
                    cs.Calendar_Time_with_Agents__c
                            = thisLog.Calendar_Duration__c != null ?
                            cs.Calendar_Time_with_Agents__c + thisLog.Calendar_Duration__c : cs.Calendar_Time_with_Agents__c;
                }
                //Check if owner type is Queue
                if (thisLog.Owner_Type__c == todft_TimeLogAggregationConstants.OWNER_TYPE_QUEUE) {
                    cs.Business_Time_with_Queues__c
                            = thisLog.Business_Hours_Duration__c != null ?
                            cs.Business_Time_with_Queues__c + thisLog.Business_Hours_Duration__c : cs.Business_Time_with_Queues__c;

                    cs.Calendar_Time_with_Queues__c
                            = thisLog.Calendar_Duration__c != null ?
                            cs.Calendar_Time_with_Queues__c + thisLog.Calendar_Duration__c : cs.Calendar_Time_with_Queues__c;
                }
                //Calculate total Calendar Time and Business Time for case
                cs.Total_Calender_Time__c
                        = thisLog.Calendar_Duration__c != null ?
                        cs.Total_Calender_Time__c + thisLog.Calendar_Duration__c : cs.Total_Calender_Time__c;

                cs.Total_BusinessTime__c
                        = thisLog.Business_Hours_Duration__c != null ?
                        cs.Total_BusinessTime__c + thisLog.Business_Hours_Duration__c : cs.Total_BusinessTime__c;

            }

            cs.No_Status_changes__c = cs.No_Status_changes__c > 1 ? cs.No_Status_changes__c - 1 : cs.No_Status_changes__c;
            if (oldCaseMap.get(caseId).Reopened_Flag__c == null || oldCaseMap.get(caseId).Reopened_Flag__c == 0) {
                cs.First_Close_Duration_Calendar__c = cs.Total_Calender_Time__c;
                cs.First_Close_Duration_Business__c = cs.Total_BusinessTime__c;
                cs.First_Close_Date_Time__c = System.Now();
                cs.First_Close_Owner__c = ownerNameByCaseIds.get(caseId);
            }
            caseListToUpdate.add(cs);
        }
        if (!caseListToUpdate.isEmpty()) {
            try {
                update caseListToUpdate;
            } catch (DmlException e) {
                System.debug('Unhandled exception occurred ' + e.getMessage());
            }
        }

    }

    /**
	 * @description Returns new case instance and set all time log field value as 0
	 * @param caseId The case record id.
	 * @return cs The Case record instance.
	 */
    public static Case createCaseInstance(Id caseId) {
        Case cs = new Case(Id = caseId);
        cs.No_Owner_changes__c = 0;
        cs.No_Status_changes__c = 0;
        cs.No_Agent_changes__c = 0;
        cs.No_Queue_changes__c = 0;
        cs.Business_Time_with_Agents__c = 0;
        cs.Calendar_Time_with_Agents__c = 0;
        cs.Calendar_Time_with_Company__c = 0;
        cs.Business_Time_with_Company__c = 0;
        cs.Total_Calender_Time__c = 0;
        cs.Total_BusinessTime__c = 0;
        cs.Business_Time_with_Queues__c = 0;
        cs.Calendar_Time_with_Queues__c = 0;
        cs.Business_Time_with_Customers__c = 0;
        cs.Calendar_Time_with_Customers__c = 0;
        return cs;
    }

    /**
	 * @description Updates Case's Reopened Flag and reset all time log fields.
	 * @param casesToProcess - sObject Records being processed
	 */
    public static void updateCaseReopenedInfo(List<Case> casesToProcess) {
        List<Case> casesToUpdate = new List<Case>();
        Case cs;
        for (Case thisCase : casesToProcess) {
            cs = createCaseInstance(thisCase.Id);
            cs.Reopened_Flag__c = thisCase.Reopened_Flag__c == null ? 1 : thisCase.Reopened_Flag__c + 1;
            casesToUpdate.add(cs);
        }
        if (!casesToUpdate.isEmpty()) {
            try {
                update casesToUpdate;
            } catch (Exception e) {
                System.debug('Unhandled exception occurred ' + e.getMessage());
            }
        }
    }

    /**
	 * @description Returns a map of case id and related owner's name
	 * @param casIds - case record ids being processed
	 */
    public static Map<Id, String> getCaseOwnerName(Set<Id> casIds) {
        Map<Id, String> ownerNameByCaseIds = new Map<Id, String>();
        for (Case cs : [SELECT Id, Owner.Name FROM Case WHERE Id IN : casIds]) {
            ownerNameByCaseIds.put(cs.Id, cs.Owner.Name);
        }
        return ownerNameByCaseIds;
    }

}