objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>MHF</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
                <value>
                    <fullName>Saks</fullName>
                </value>
                <value>
                    <fullName>Off 5th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/SCCQueryUtilClass_Test.cls
@IsTest
private class SCCQueryUtilClass_Test  {

    @IsTest
    static void testQueries() {

        Case newCase = new Case(Order_Number__c='12345', Business_Unit__c='SAKS');
        insert newCase;

        SCCQueryUtilClass.getInstance()
                .getQueryInstance()
                .setObjectName('Case').setAllFields();

        String query = SCCQueryUtilClass.getInstance()
                        .getQueryInstance()
                        .setObjectName('Case')
                        .setRelatedFields(new Set<String>{'Id', 'Order_Number__c', 'Business_Unit__c'})
                        .setClause('Business_Unit__c', '=', 'SAKS')
                        .setLimit('1')
                        .getQuery();




    }

}