objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Loyalty_Number__c</fullName>
        <label>Loyalty Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loyalty_Tier__c</fullName>
        <label>Loyalty Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Associate/Retiree</fullName>
                </value>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>PLCC non-Premier</fullName>
                </value>
                <value>
                    <fullName>Plus</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Integration_Error__c.object
<CustomObject>
    <description>Stores integration errors.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The URL of the endpoint where the payload was sent</description>
        <inlineHelpText>The URL of the endpoint where the payload was sent</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>The Request of the callout if applicable</description>
        <inlineHelpText>The Request of the callout if applicable</inlineHelpText>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_UpdateLoyaltyInfoOnContact.cls
/**
 * @author Nigel Rodrigues, Traction on Demand
 * @description Updates the contact with Loyalty information
 */

public with sharing class trac_UpdateLoyaltyInfoOnContact {

    public void updateContacts(List<Id> contactsToUpdate)
    {

        List<Contact> contactList = [SELECT Id,Available_Points__c,
                                        Loyalty_Tier__c,Gift_card_amount__c,Next_gift_card_amount__c,
                                        Points_to_next_reward__c, SFCC_Customer_Number__c,Loyalty_Number__c
                                    FROM Contact
                                    WHERE Id IN :contactsToUpdate];

        trac_WS_GetSaksLoyalty request = new trac_WS_GetSaksLoyalty();
        List<Contact> contactsToBeUpdated = new List<Contact>();

        try{

            for(Contact contact : contactList)
            {
                request.loyaltyId = contact.Loyalty_Number__c;
                if(request.send() && request.getSaksLoyaltyResponse != null)
                {
                    contact.Available_Points__c      = request.getSaksLoyaltyResponse.response.results.member_info.available_points;
                    contact.Loyalty_Tier__c          = request.getSaksLoyaltyResponse.response.results.member_info.tier_status;
                    contact.Gift_card_amount__c      = request.getSaksLoyaltyResponse.response.results.member_info.gift_card_amount;
                    contact.Next_gift_card_amount__c = request.getSaksLoyaltyResponse.response.results.member_info.next_gift_card_amount;
                    contact.Points_to_next_reward__c = request.getSaksLoyaltyResponse.response.results.member_info.points_to_next_reward;
                    contactsToBeUpdated.add(contact);
                }
            }

            update contactsToBeUpdated;

        }
        catch(Exception e)
        {
            Integration_Error__c integrationError = trac_IntegrationError.addError(new Integration_Error__c(
                    Description__c = e.getMessage() + '\n' + e.getStackTraceString(),
                    Endpoint__c = request.dynamicEndpoint,
                    //Request__c = JSON.serializePretty(reqWrapper),
                    Service__c = 'Updating Loyalty SAKS on contact'
            ));
            insert integrationError;
        }

    }

}