objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reference_Data__mdt.object
<CustomObject>
    <description>Data mappings from other systems</description>
    <fields>
        <fullName>Salesforce_Value__c</fullName>
        <description>The value of the data in Salesforce</description>
        <inlineHelpText>The value of the data in Salesforce</inlineHelpText>
        <label>Salesforce Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Value__c</fullName>
        <description>The value of the data in the source system</description>
        <inlineHelpText>The value of the data in the source system</inlineHelpText>
        <label>System Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <description>The source system for the data</description>
        <inlineHelpText>The source system for the data</inlineHelpText>
        <label>System</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>UCID</fullName>
                </value>
                <value>
                    <fullName>OMS</fullName>
                </value>
                <value>
                    <fullName>Finesse</fullName>
                </value>
                <value>
                    <fullName>Blue Martini</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of data being referenced</description>
        <inlineHelpText>The type of data being referenced</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reference Data</label>
    <pluralLabel>Reference Data</pluralLabel>
</CustomObject>

classes/trac_PhoneUtils.cls
/**
 *  @description Utility class for Phone and CTI related methods
 *  @author      Jeremy Horan, Traction on Demand.
 *  @date        8/16/2019
 */
public without sharing class trac_PhoneUtils {

    public static final List<Reference_Data__mdt> referenceDataSettings = [SELECT Salesforce_Value__c, System_Value__c FROM Reference_Data__mdt WHERE System__c = 'Finesse' AND Type__c = 'Business Unit Prefix'];

    public static String getPhoneWithPrefix(Contact contact) {
        String phoneNumber;

        if (contact != null && contact.Business_Unit__c != null && contact.Phone != null && referenceDataSettings != null) {
            String cleanPhoneNumber = TLString.getUnformattedPhoneNumber(contact.Phone);
            phoneNumber = cleanPhoneNumber;
            for (Reference_Data__mdt referenceData : referenceDataSettings) {
                if (contact.Business_Unit__c == referenceData.Salesforce_Value__c) {
                    phoneNumber = referenceData.System_Value__c + getPrefixFromPhone(cleanPhoneNumber) + cleanPhoneNumber;
                    break;
                }
            }
        }

        return phoneNumber;
    }

    private static String getPrefixFromPhone(String phoneNumber) {
        String prefix = '91';

        if (phoneNumber != null) {
            if (phoneNumber.length() > 11) {
                prefix = '9011';
            }
            if (phoneNumber.startsWith('011')) {
                prefix = prefix.removeEnd('011');
            }
            if (phoneNumber.startsWith('1')) {
                prefix = prefix.removeEnd('1');
            }
        }

        return prefix;
    }
}