objects/External_Link_Setting__mdt.object
<CustomObject>
    <description>Links to other sites to be used on the widget component</description>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>50</defaultValue>
        <description>The order in which links will be displayed (lowest number first)</description>
        <inlineHelpText>The order in which links will be displayed (lowest number first)</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>The link to the website that should open</description>
        <inlineHelpText>The link to the website that should open</inlineHelpText>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>External Link Setting</label>
    <pluralLabel>External Link Settings</pluralLabel>
</CustomObject>

classes/trac_QuickLinksController.cls
/**
 * @description Apex controller for trac_QuickLinks lightning component
 * @author      Rajat Agrawal, Traction on Demand
 * @date        2019-06-27
 */
public with sharing class trac_QuickLinksController {

    /**
     * @description Method to return the quick links from the metadata
     * @return      List<External_Link_Setting__mdt>, List of quick links records
     */
    @AuraEnabled
    public static List<External_Link_Setting__mdt> getQuickLinks(){
        List<External_Link_Setting__mdt> externalLinkSettings = new List<External_Link_Setting__mdt>();
        externalLinkSettings = [SELECT Id, Label, URL__c FROM External_Link_Setting__mdt ORDER BY Order__c ASC, Label ASC];
        return externalLinkSettings;
    }
}