objects/Field_Tracker_Mapping__mdt.object
<CustomObject>
    <description>Field Tracker Configuration.  Each metadata record corresponds to an Object/Field that will be tracked.  Map the fields on the Time Log object to the fields you would like to track on the parent object.</description>
    <fields>
        <fullName>Parent_Record_Field__c</fullName>
        <description>API Name of the field on the parent record.</description>
        <inlineHelpText>Specify the field you want to track (E.g. Status)</inlineHelpText>
        <label>Parent Record Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Record_Object__c</fullName>
        <description>Parent record object type</description>
        <inlineHelpText>Specify the Object Type you want to track (E.g. Case)</inlineHelpText>
        <label>Parent Record Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Log_Field_Mapping__c</fullName>
        <description>Field on Time Log object that parent record&apos;s value will be written</description>
        <inlineHelpText>Field on Time Log object that parent record&apos;s value will be written (E.g. Status__c)</inlineHelpText>
        <label>Time Log Field Mapping</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Log_Field_New_Value__c</fullName>
        <description>Field on Time Log object that parent record&apos;s updated value will be written</description>
        <inlineHelpText>Field on Time Log object that parent record&apos;s updated value will be written (E.g. Status_New__c)</inlineHelpText>
        <label>Time Log Field New Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Field Tracker Mapping</label>
    <pluralLabel>Field Tracker Mappings</pluralLabel>
</CustomObject>

objects/Trigger_Record_Type__mdt.object
<CustomObject>
    <description>Used to filter certain triggers by object and record type</description>
    <fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>The API name of the object</description>
        <inlineHelpText>Specify the Object Type (E.g. Case)</inlineHelpText>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <description>The DeveloperName of the Record Type</description>
        <inlineHelpText>Specify the DeveloperName of the record type (E.g. Technical_Support)</inlineHelpText>
        <label>Record Type Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Trigger Record Type</label>
    <pluralLabel>Trigger Record Types</pluralLabel>
</CustomObject>

classes/todft_FieldLoggerUtils.cls
/**
 * @author Steve Doucette, Traction on Demand 
 * @date 2/20/2019
 */
public with sharing class todft_FieldLoggerUtils {

	// Constants
	public static final String APPNAME = 'FIELD TRACKER';

	// Used to filter records by recordType
	public static Map<String, List<Trigger_Record_Type__mdt>> recordTypeSettingsByObject {
		get {
			if (recordTypeSettingsByObject == null) {
				recordTypeSettingsByObject = new Map<String, List<Trigger_Record_Type__mdt>>();

				for (Trigger_Record_Type__mdt mapping : [
						SELECT Object_Name__c,
								Record_Type_Name__c, Enable__c
						FROM Trigger_Record_Type__mdt
				]) {
					if (!recordTypeSettingsByObject.containsKey(mapping.Object_Name__c)) {
						recordTypeSettingsByObject.put(mapping.Object_Name__c, new List<Trigger_Record_Type__mdt>());
					}
					recordTypeSettingsByObject.get(mapping.Object_Name__c).add(mapping);
				}
			}
			return recordTypeSettingsByObject;
		}
		set;
	}

	// Used to determine what settings to use per object being processed
	public static Map<String, List<Field_Tracker_Mapping__mdt>> settingsByObject {
		get {
			if (settingsByObject == null) {
				settingsByObject = new Map<String, List<Field_Tracker_Mapping__mdt>>();

				//SNAPSHOT-3 Added Time_Log_Field_New_Value__c in querying metadata in Apex class
				//to set the corresponding Time Log field with the updated value, when the parent record is updated.
				for (Field_Tracker_Mapping__mdt mapping : [
						SELECT Parent_Record_Object__c,
								Parent_Record_Field__c,
								Time_Log_Field_Mapping__c,
								Time_Log_Field_New_Value__c
						FROM Field_Tracker_Mapping__mdt
				]) {
					if (!settingsByObject.containsKey(mapping.Parent_Record_Object__c)) {
						settingsByObject.put(mapping.Parent_Record_Object__c, new List<Field_Tracker_Mapping__mdt>());
					}
					settingsByObject.get(mapping.Parent_Record_Object__c).add(mapping);
				}
			}
			return settingsByObject;
		}
		set;
	}

	// Used for dynamic querying per object
	public static Map<String, Set<String>> fieldMappingsByObject {
		get {
			if (fieldMappingsByObject == null) {
				fieldMappingsByObject = new Map<String, Set<String>>();
				Set<String> objNames = settingsByObject.keySet();

				for (String objName : objNames) {
					fieldMappingsByObject.put(objName, new Set<String>());
					for (Field_Tracker_Mapping__mdt setting : settingsByObject.get(objName)) {
						fieldMappingsByObject.get(objName).add(setting.Parent_Record_Field__c);
					}
				}
			}
			return fieldMappingsByObject;
		}
		set;
	}

	/**
	 * dynamic upsert helper
	 * @description Casts a List<SObject> to a concrete type and upserts
	 */
	public static void dynamicUpsert(List<SObject> records, Schema.SObjectType sObjectType, List<SObject> parentRecordList) {
		try {
			String listType = 'List<' + sObjectType + '>';
			List<SObject> castRecords = (List<SObject>) Type.forName(listType).newInstance();
			castRecords.addAll(records);
			upsert castRecords;
		} catch (Exception e) {
		}
	}
}