objects/Integration_Error__c.object
<CustomObject>
    <description>Stores integration errors.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The URL of the endpoint where the payload was sent</description>
        <inlineHelpText>The URL of the endpoint where the payload was sent</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>The Request of the callout if applicable</description>
        <inlineHelpText>The Request of the callout if applicable</inlineHelpText>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_OrderLineStatusHistoryCtlr.cls
/**
 *  @description Aura controller for trac_OrderLineStatusHistory component
 *  @author      Jeremy Horan, Traction on Demand.
 *  @date        2/4/2020
 */
public with sharing class trac_OrderLineStatusHistoryCtlr {


    @AuraEnabled
    public static TLAuraResponse getLineHistory(String businessUnit, String orderNumber, String lineItemNumber) {
        TLAuraResponse response = new TLAuraResponse(true);

        trac_WS_OrderLineHistory orderLineHistory = new trac_WS_OrderLineHistory();
        try {

            trac_WS_OrderLineHistory.req_OrderWrapper reqWrapper = new trac_WS_OrderLineHistory.req_OrderWrapper();
            reqWrapper.EnterpriseCode = trac_WS_OrderUtils.getEnterpriseCodeFromBusinessUnit(businessUnit);
            reqWrapper.DocumentType = trac_WS_OrderUtils.getOrderType();
            reqWrapper.OrderNo = orderNumber;

            if (lineItemNumber != null) {
                trac_WS_OrderLineHistory.req_OrderLineWrapper reqOrderLineWrapper = new trac_WS_OrderLineHistory.req_OrderLineWrapper();
                reqOrderLineWrapper.PrimeLineNo = lineItemNumber;
                reqOrderLineWrapper.SubLineNo = trac_WS_OrderUtils.getSubLineNumber();

                trac_WS_OrderLineHistory.req_OrderLinesWrapper reqOrderLinesWrapper = new trac_WS_OrderLineHistory.req_OrderLinesWrapper();
                reqOrderLinesWrapper.OrderLine = reqOrderLineWrapper;

                reqWrapper.OrderLines = reqOrderLinesWrapper;
            }

            trac_WS_OrderLineHistory.OrderLineHistoryRequest req = new trac_WS_OrderLineHistory.OrderLineHistoryRequest();
            req.Order = reqWrapper;

            orderLineHistory.orderLineHistoryRequest = req;

            orderLineHistory.send();

            response.returnValuesMap.put('lineStatusHistory', orderLineHistory.orderLineHistoryResponse);
        }
        catch (Exception e) {
            Integration_Error__c integrationError = trac_IntegrationError.addError(new Integration_Error__c(
                    Description__c = e.getMessage() + '\n' + e.getStackTraceString(),
                    Endpoint__c = orderLineHistory.ENDPOINT,
                    Request__c = JSON.serializePretty(orderLineHistory.orderLineHistoryRequest),
                    Service__c = 'Order Line Status History'
            ));
            insert integrationError;

            String errorMessage = trac_WS_WebServiceHelper.DEFAULT_ERROR + integrationError.Id;

            response = new TLAuraResponse(false, errorMessage);
        }

        return response;
    }
}