objects/Integration_Error__c.object
<CustomObject>
    <description>Stores integration errors.</description>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_AddNoteCtlrTest.cls
@IsTest
private class trac_AddNoteCtlrTest {

    static final TLTestFactory factory = new TLTestFactory();

    @IsTest
    static void testAddNotes() {
        Test.setMock(HttpCalloutMock.class, new MockOrderResponses('/update'));
        TLAuraResponse response  = trac_AddNoteCtlr.addNotes('SAKS','1234', '12345', '', '');
        System.assertEquals(true, response.isSuccess);

    }

    @IsTest
    static void testAddNotesError() {
        Test.setMock(HttpCalloutMock.class, new MockOrderResponsesError('/update'));
        TLAuraResponse response  =  trac_AddNoteCtlr.addNotes('SAKS','1234', '', '', '');
        System.assertEquals(false, response.isSuccess);

        Integration_Error__c error = [SELECT Id,Service__c FROM Integration_Error__c LIMIT 1];
        System.assertEquals('Add Notes To Order', error.Service__c);

    }

    @IsTest
    static void testApplyReviewNotesHold() {
        Test.setMock(HttpCalloutMock.class, new MockOrderResponses('/update'));
        TLAuraResponse response  = trac_AddNoteCtlr.applyReviewNotesHold('SAKS','1234', 'test notes');
        System.assertEquals(true, response.isSuccess);

    }

    @IsTest
    static void testApplyReviewNotesHoldError() {
        Test.setMock(HttpCalloutMock.class, new MockOrderResponsesError('/update'));
        TLAuraResponse response  =  trac_AddNoteCtlr.applyReviewNotesHold('SAKS','1234', 'test notes');
        System.assertEquals(false, response.isSuccess);

        Integration_Error__c error = [SELECT Id,Service__c FROM Integration_Error__c LIMIT 1];
        System.assertNotEquals(null, error);

    }
}