objects/Integration_Error__c.object
<CustomObject>
    <description>Stores integration errors.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The URL of the endpoint where the payload was sent</description>
        <inlineHelpText>The URL of the endpoint where the payload was sent</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>The Request of the callout if applicable</description>
        <inlineHelpText>The Request of the callout if applicable</inlineHelpText>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_EventController.cls
/**
 * @author Nigel Rodrigues, Traction on Demand
 * @date 4-June-2020
 * @description Controller related to customer event history.
 */

public with sharing class trac_EventController {

    @AuraEnabled
    public static TLAuraResponse getTransactionHistory(String email, String customerId)
    {
        TLAuraResponse response = new TLAuraResponse(true);


        trac_WS_LoyaltyEvent request = new trac_WS_LoyaltyEvent();
        if( request.send(email, customerId) ){

            if( request.eventResponse != null)
            {
                for(trac_WS_LoyaltyEvent.res_dataWrapper dataItem : request.eventResponse.data )
                {
                    dataItem.showDetails = false;
                }
            }
            response.returnValuesMap.put('transactions', request.eventResponse);
        }
        else{
            Integration_Error__c integrationError = trac_IntegrationError.addError(new Integration_Error__c(
                    Description__c = request.jsonError,
                    Endpoint__c = trac_WS_WebServiceHelper.webServiceSettings.Bay_Loyalty_Base_Endpoint__c
                            + trac_WS_WebServiceHelper.webServiceSettings.Bay_Loyalty_API_Version__c
                            + trac_WS_WebServiceHelper.webServiceSettings.Bay_Event_History__c + '',
                    Request__c = '',
                    Service__c = 'Loyalty Customer Event History'
            ));
            insert integrationError;

            String errorMessage = trac_WS_WebServiceHelper.DEFAULT_ERROR + integrationError.Id;
            response = new TLAuraResponse(false, errorMessage);
        }

        return response;
    }

}