objects/Integration_Error__c.object
<CustomObject>
    <description>Stores integration errors.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The URL of the endpoint where the payload was sent</description>
        <inlineHelpText>The URL of the endpoint where the payload was sent</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>The Request of the callout if applicable</description>
        <inlineHelpText>The Request of the callout if applicable</inlineHelpText>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_LoyaltySearchController.cls
public with sharing class trac_LoyaltySearchController {

    @AuraEnabled
    public static TLAuraResponse getLoyalty(String email, String loyaltyId, String phoneNum) {
        TLAuraResponse response = new TLAuraResponse(true);
        trac_WS_GetLoyalty request = new trac_WS_GetLoyalty();

        request.loyaltyRequest = new trac_WS_GetLoyalty.LoyaltyRequest(
                email,
                loyaltyId,
                phoneNum,
                '4');
        try {
            if(request.send() && request.loyaltyRequest != null) {
                response.returnValuesMap.put('loyalty', request.loyaltyResponse);
            } else if (!request.send() && request.isNotFound()) {
                response = new TLAuraResponse(false, 'loyalty not found');
            } else {
                throw new LoyaltySearchException(request.jsonError);
            }
        } catch (Exception e) {
            Integration_Error__c integrationError = trac_IntegrationError.addError(new Integration_Error__c(
                    Description__c = e.getMessage() + '\n' + e.getStackTraceString(),
                    Endpoint__c = request.ENDPOINT,
                    Request__c = JSON.serializePretty(request.loyaltyRequest),
                    Service__c = 'Loyalty Lookup'
            ));
            insert integrationError;

            String errorMessage = trac_WS_WebServiceHelper.DEFAULT_ERROR + integrationError.Id;

            response = new TLAuraResponse(false, errorMessage);
        }

        response.returnValuesMap.put('statusCode', request.getStatusCode());

        return response;
    }

    @AuraEnabled
    public static TLAuraResponse testAPI() {
        TLAuraResponse response = new TLAuraResponse(true);
        trac_WS_GetLoyaltyById request = new trac_WS_GetLoyaltyById();

        if(request.send()) {
            response.returnValuesMap.put('loyalty', request.loyaltyResponse);
        }

        return response;
    }

    public class LoyaltySearchException extends Exception {}
}