objects/Integration_Error__c.object
<CustomObject>
    <description>Stores integration errors.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The URL of the endpoint where the payload was sent</description>
        <inlineHelpText>The URL of the endpoint where the payload was sent</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>The Request of the callout if applicable</description>
        <inlineHelpText>The Request of the callout if applicable</inlineHelpText>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_CancelOrderCtlr.cls
/**
 *  @description Lightning controller for trac_CancelOrder
 *  @author      Jeremy Horan, Traction on Demand.
 *  @date        7/17/2019
 */
public with sharing class trac_CancelOrderCtlr {

    @AuraEnabled
    public static TLAuraResponse cancelOrder(String businessUnit, String orderNumber, String primeLineNumber, String subLineNumber, String cancelReason, String cancelReasonCode) {
        TLAuraResponse response = new TLAuraResponse(true);

        trac_WS_CancelOrder cancelOrder = new trac_WS_CancelOrder();

        try {
            
            cancelOrder.cancelOrderRequest.Order.OrderNo = orderNumber;
            cancelOrder.cancelOrderRequest.Order.EnterpriseCode = trac_WS_OrderUtils.getEnterpriseCodeFromBusinessUnit(businessUnit);
            cancelOrder.cancelOrderRequest.Order.DocumentType = trac_WS_OrderUtils.getOrderType();
            cancelOrder.cancelOrderRequest.Order.ModificationReasonCode = (cancelReasonCode != null) ? cancelReasonCode : trac_WS_OrderUtils.getModificationCode();
            cancelOrder.cancelOrderRequest.Order.ModificationReasonText = cancelReason;

            if (primeLineNumber != null && !String.isEmpty(primeLineNumber)) {
                cancelOrder.cancelOrderRequest.Order.Action = trac_WS_OrderUtils.getModifyAction();
                cancelOrder.cancelOrderRequest.Order.OrderLines.OrderLine.PrimeLineNo = primeLineNumber;
                cancelOrder.cancelOrderRequest.Order.OrderLines.OrderLine.SubLineNo = trac_WS_OrderUtils.getSubLineNumber();
                cancelOrder.cancelOrderRequest.Order.OrderLines.OrderLine.Action = trac_WS_OrderUtils.getCancelAction();
            }
            else {
                cancelOrder.cancelOrderRequest.Order.OrderLines = null;
                cancelOrder.cancelOrderRequest.Order.Action = trac_WS_OrderUtils.getCancelAction();
            }

            cancelOrder.send();

        } catch (Exception e) {
            Integration_Error__c integrationError = trac_IntegrationError.addError(new Integration_Error__c(
                    Description__c = e.getMessage() + '\n' + e.getStackTraceString(),
                    Endpoint__c = cancelOrder.ENDPOINT,
                    Request__c = JSON.serializePretty(cancelOrder.cancelOrderRequest),
                    Service__c = 'Cancel Order'
            ));
            insert integrationError;

            String errorMessage = trac_WS_WebServiceHelper.DEFAULT_ERROR + integrationError.Id;

            response = new TLAuraResponse(false, errorMessage);
        }

        return response;
    }
}