objects/Integration_Error__c.object
<CustomObject>
    <description>Stores integration errors.</description>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Readable title for identification</description>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_IntegrationError.cls
/**
 *  @description Methods to assist with Integration_Error__c functionality
 *  @author 	 Bejal Lewis, Traction on Demand.
 *  @date        2017-08-07
 */
public without sharing class trac_IntegrationError {

    public static List<Integration_Error__c> integrationErrors = new List<Integration_Error__c>();

	/**
	 *  @description Creates an integration error and inserts into database
	 *  @author 	 Bejal Lewis, Traction on Demand.
	 *  @date        2017-08-07
	 */
	public static Integration_Error__c addError(Integration_Error__c integrationError) {
		String currentTime = String.valueOf(Datetime.now());

		integrationError.Title__c = integrationError.Service__c + ': ' + currentTime;

        integrationErrors.add(integrationError);

		return integrationError;
	}

    public static void insertIntegrationErrors() {
        if (!integrationErrors.isEmpty()) {
            insert integrationErrors;
            integrationErrors = new List<Integration_Error__c>();
        }
    }
}