objects/Integration_Error__c.object
<CustomObject>
    <description>Stores integration errors.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The URL of the endpoint where the payload was sent</description>
        <inlineHelpText>The URL of the endpoint where the payload was sent</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>The Request of the callout if applicable</description>
        <inlineHelpText>The Request of the callout if applicable</inlineHelpText>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_PurchaseOrderCtrl.cls
/**
* @description Controller for trac_PurchaseOrder
* @author      Abhishek Singh Solanki, Traction on Demand
* @date        2020/03/27
*/

public with sharing class trac_PurchaseOrderCtrl {
    @AuraEnabled
    public static TLAuraResponse getPurchaseOrderLine(String businessUnit, String orderNumber, String DocumentType) {
        TLAuraResponse response = new TLAuraResponse(true);

        trac_WS_PurchaseOrder purchaseOrderLine = new trac_WS_PurchaseOrder();
        try {

            trac_WS_PurchaseOrder.req_OrderWrapper reqWrapper = new trac_WS_PurchaseOrder.req_OrderWrapper();
            reqWrapper.EnterpriseCode = trac_WS_OrderUtils.getEnterpriseCodeFromBusinessUnit(businessUnit);
            reqWrapper.DocumentType = DocumentType;
            reqWrapper.OrderNo = orderNumber;

            trac_WS_PurchaseOrder.purchaseOrderRequest req = new trac_WS_PurchaseOrder.purchaseOrderRequest();
            req.Order = reqWrapper;

            purchaseOrderLine.purchaseOrderRequest = req;

            purchaseOrderLine.send();

            response.returnValuesMap.put('orderResponse', purchaseOrderLine.purchaseOrderResponse);

        } catch (Exception e) {
            Integration_Error__c integrationError = trac_IntegrationError.addError(new Integration_Error__c(
                    Description__c = e.getMessage() + '\n' + e.getStackTraceString(),
                    Endpoint__c = purchaseOrderLine.ENDPOINT,
                    Request__c = JSON.serializePretty(purchaseOrderLine.purchaseOrderRequest),
                    Service__c = 'Purchase Order (VendorNet)'
            ));
            insert integrationError;

            String errorMessage = trac_WS_WebServiceHelper.DEFAULT_ERROR + integrationError.Id;

            response = new TLAuraResponse(false, errorMessage);
        }

        return response;
    }

}