objects/Reference_Data__mdt.object
<CustomObject>
    <description>Data mappings from other systems</description>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language of the value, defaults to english</description>
        <inlineHelpText>The language of the value, defaults to english</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salesforce_Value__c</fullName>
        <description>The value of the data in Salesforce</description>
        <inlineHelpText>The value of the data in Salesforce</inlineHelpText>
        <label>Salesforce Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Value__c</fullName>
        <description>The value of the data in the source system</description>
        <inlineHelpText>The value of the data in the source system</inlineHelpText>
        <label>System Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <description>The source system for the data</description>
        <inlineHelpText>The source system for the data</inlineHelpText>
        <label>System</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>UCID</fullName>
                </value>
                <value>
                    <fullName>OMS</fullName>
                </value>
                <value>
                    <fullName>Finesse</fullName>
                </value>
                <value>
                    <fullName>Blue Martini</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of data being referenced</description>
        <inlineHelpText>The type of data being referenced</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reference Data</label>
    <pluralLabel>Reference Data</pluralLabel>
</CustomObject>

classes/trac_ReferenceData.cls
/**
 *  @description Reference Data class to get values for other systems. Uses
 *  @author      Jeremy Horan, Traction on Demand.
 *  @date        6/17/2019
 */
public with sharing class trac_ReferenceData {

    public static Map<String, Map<String, Reference_Data__mdt>> getReferenceDataMappedByValueByType(String systemName, String keyApiName) {
        Map<String, Map<String, Reference_Data__mdt>> referenceDataByValueByType = new Map<String, Map<String, Reference_Data__mdt>>();

        List<Reference_Data__mdt> referenceDataList = getReferenceDataBySystem(systemName);

        for (Reference_Data__mdt referenceData : referenceDataList) {
            if (referenceData.Type__c != null && referenceData.System_Value__c != null) {
                if (!referenceDataByValueByType.containsKey(referenceData.Type__c)) {
                    referenceDataByValueByType.put(referenceData.Type__c, new Map<String, Reference_Data__mdt>());
                }
                referenceDataByValueByType.get(referenceData.Type__c).put((String)referenceData.get(keyApiName), referenceData);
            }
        }

        return referenceDataByValueByType;
    }

    public static List<Reference_Data__mdt> getReferenceDataBySystem(String systemName) {
        List<Reference_Data__mdt> referenceData = [
                SELECT Id, Language__c, Type__c, System_Value__c, Salesforce_Value__c, System__c
                FROM Reference_Data__mdt
                WHERE System__c = :systemName
        ];
        return referenceData;
    }
}