objects/Urgent_Message__c.object
<CustomObject>
    <fields>
        <fullName>Activation_Date__c</fullName>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Banner__c</fullName>
        <label>Banner</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hudson&apos;s Bay</fullName>
                </value>
                <value>
                    <fullName>Lord + Taylor</fullName>
                </value>
                <value>
                    <fullName>MHF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Include_In_Community__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the message will also be displayed in the community for the associated business unit</description>
        <inlineHelpText>When checked, the message will also be displayed in the community for the associated business unit</inlineHelpText>
        <label>Include In Community</label>
        <type>Checkbox</type>
    </fields>
    <label>Urgent Message</label>
    <nameField>
        <label>Urgent Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Urgent Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/trac_UrgentMessageSelector.cls
/**
 *  @description Holds Queries for Urgent Messages
 *  @author 	 Jeremy Horan, Traction on Demand.
 *  @date        2016-08-03
 */
public with sharing class trac_UrgentMessageSelector {

	/**
	 *  @description Gets a list of Urgent Messages based on banner
	 *  @author 	 Jeremy Horan, Traction on Demand.
	 *  @date        2016-08-03
	 */
	public static List<Urgent_Message__c> findAllActiveByBanner(String banner, Date activeDate) {
		List<Urgent_Message__c> urgentMessages = [
            SELECT Id, Name 
            FROM Urgent_Message__c 
            WHERE Banner__c INCLUDES (:banner) AND Activation_Date__c <= :activeDate AND (Expiration_Date__c >= :activeDate OR Expiration_Date__c = null)
        ];

		return urgentMessages;
	}

	/**
	 *  @description Gets a list of Urgent Messages based on banner
	 *  @author 	 Jeremy Horan, Traction on Demand.
	 *  @date        2016-08-03
	 */
	public static List<Urgent_Message__c> findAllActiveByBannerCommunity(String banner, Date activeDate) {
		List<Urgent_Message__c> urgentMessages = [
				SELECT Id, Name
				FROM Urgent_Message__c
				WHERE Banner__c INCLUDES (:banner) AND Activation_Date__c <= :activeDate AND (Expiration_Date__c >= :activeDate OR Expiration_Date__c = null) AND Include_In_Community__c = true
		];

		return urgentMessages;
	}

	/**
	 *  @description Returns Urgent Message with given ID
	 *  @author 	 Jeremy Horan, Traction on Demand.
	 *  @date        2016-08-04
	 */
	public static Urgent_Message__c getUrgentMessageById(Id urgentMessageId) {
		List<Urgent_Message__c> urgentMessages = [SELECT Id, Body__c FROM Urgent_Message__c WHERE Id = :urgentMessageId];
		if (urgentMessages.size() > 0) {
			return urgentMessages[0];
		}
		return null;
	}
}