objects/Web_Service_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Settings for Web Services
- Default Endpoints &amp; Other Parameters</description>
    <fields>
        <fullName>API_Key__c</fullName>
        <description>HBC Gateway API Key</description>
        <label>API Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Base_Url__c</fullName>
        <label>Base Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CNS_Email_Search_Endpoint__c</fullName>
        <description>Relative endpoint for the email search API</description>
        <label>CNS Email Search Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CNS_Get_Email_Body__c</fullName>
        <label>CNS Get Email Body</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CNS_Send_Email_Endpoint__c</fullName>
        <description>Endpoint for the CNS Send Email API</description>
        <label>CNS Send Email Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Order_Endpoint__c</fullName>
        <description>OMS Create Order relative Endpoint</description>
        <label>Create Order Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Search_API_key__c</fullName>
        <label>Email Search API key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Get_Order_Details_Endpoint__c</fullName>
        <description>OMS Get Order Details relative Endpoint</description>
        <label>Get Order Details Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Get_Order_List_Endpoint__c</fullName>
        <description>OMS Get Order List Service relative Endpoint</description>
        <label>Get Order List Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPA_Get_Adjustment_Endpoint__c</fullName>
        <description>Sales Price Adjustment Calculator Relative Endpoint for getting an adjustment by ID</description>
        <label>SPA Get Adjustment Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPA_Get_Order_Adjustments_Endpoint__c</fullName>
        <description>Sales Price Adjustment Calculator Relative Endpoint for getting an adjustment by Order Number</description>
        <label>SPA Get Order Adjustments Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPA_Update_Adjustment_Endpoint__c</fullName>
        <description>Sales Price Adjustment Calculator Relative Endpoint for updating an adjustment by ID</description>
        <label>SPA Update Adjustment Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tokenex_Endpoint__c</fullName>
        <description>Full TokenEx Endpoint</description>
        <label>Tokenex Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tokenex_Token_Scheme__c</fullName>
        <description>Token Scheme used to encrypt data</description>
        <label>Tokenex Token Scheme</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UCID_Create_Endpoint__c</fullName>
        <description>UCID Create Service relative Endpoint</description>
        <label>UCID Create Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UCID_Query_Endpoint__c</fullName>
        <description>UCID Query Service relative endpoint</description>
        <label>UCID Query Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UCID_Update_Endpoint__c</fullName>
        <description>UCID Update Service relative endpoint</description>
        <label>UCID Update Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Update_Order_Endpoint__c</fullName>
        <description>OMS Update Order relative Endpoint</description>
        <label>Update Order Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Web Service Settings</label>
</CustomObject>

classes/trac_TestUtils.cls
/**
 *  @description Test Utilities
 *  @author      Jeremy Horan, Traction on Demand.
 *  @date        5/29/2019
 */
@IsTest
public class trac_TestUtils {

    /**
	 *  @description initializes web service settings
	 *  @author 	 Jeremy Horan, Traction on Demand.
	 *  @date        2017-05-16
	 */
    public static Web_Service_Settings__c setupWebServiceSettings() {

        Web_Service_Settings__c webServiceSettings = new Web_Service_Settings__c(
                API_Key__c = 'test',
                Create_Order_Endpoint__c = '/orders',
                Get_Order_Details_Endpoint__c = '/orders/details',
                UCID_Create_Endpoint__c = '/customers/me',
                Timeout__c = 120000,
                Base_Url__c = 'https://uat.thebay.com/live',
                Update_Order_Endpoint__c = '/orders',
                Get_Order_List_Endpoint__c = '/orders/list',
                UCID_Update_Endpoint__c = '/customers/me',
                UCID_Query_Endpoint__c = '/customers/search',
                CNS_Send_Email_Endpoint__c = 'https://api.backoffice.giltaws.com/api-customer-notification/stqa/resend_rendered_message/',
                CNS_Email_Search_Endpoint__c = 'https://api.backoffice.giltaws.com/api-customer-notification/stqa/search_log',
                Email_Search_API_key__c = 'test',
                CNS_Get_Email_Body__c = 'https://api.backoffice.giltaws.com/api-customer-notification/stqa/preview/email',
                Tokenex_Endpoint__c = 'https://www.tokenextest.com',
                Tokenex_Token_Scheme__c = '9996',
                SPA_Get_Adjustment_Endpoint__c = 'https://www.spatestget.com',
                SPA_Update_Adjustment_Endpoint__c  = 'https://www.spatestupdate.com',
                SPA_Get_Order_Adjustments_Endpoint__c  = 'https://www.spatestgetlist.com',
                Bay_Loyalty_API_Version__c = '2019-01-01',
                Bay_Loyalty_Base_Endpoint__c = 'https://merkle.base.endpoint/',
                Bay_Loyalty_Record_Event_Endpoint__c = '/api/record.json',
                Bay_Loyalty_Secret_Key__c = 'merklesecretkey',
                Bay_Loyalty_UUID__c = 'merkleuuid',
                Bay_Loyalty_X_API_Key__c = 'merklexapikey',
                Bay_Loyalty_X_APIGW_API_ID__c = 'merklexapigwapiid'
        );

        return webServiceSettings;
    }
}